### ISSUE TITLE
Yoke rotation point not centralize in the yoke bar

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#10]
Yoke rotation point not centralize in the yoke bar, which then moves around instead of staying in the same place.

all good:
![fgfs-screen-007](https://cloud.githubusercontent.com/assets/5700795/12008351/c87a33e8-ac35-11e5-855d-821e90409aad.png)

wrong position:
![fgfs-screen-006](https://cloud.githubusercontent.com/assets/5700795/12008352/d0e56a02-ac35-11e5-988b-b08c75ccd6a0.png)

**Comment by HHS81** [comment]
Fixed in Master-Branch, also changed tilting of Yoke (no influence on uvmapping!)

**Comment by gilbertohasnofb** [comment]
> no influence on uvmapping!

Perfect, thanks! Talking of which, when you have time please check the PR for the textures, I am very curious for your opinions :smile:
