### ISSUE TITLE
Doesn't load in 2016.1.2

### ISSUE THREAD

**Issue by Maurycy-Sokolowski** [HHS81/c182#103]
1) Downloaded repo as zip
2) copied unzipped directory into $FG_AIRCRAFT as 182s

It looks like this

![fg 1](https://cloud.githubusercontent.com/assets/6224146/16606002/08e624ec-42e9-11e6-8607-74568f2de31c.JPG)
![fg 2](https://cloud.githubusercontent.com/assets/6224146/16606003/08e8366a-42e9-11e6-9e7e-55b874dd3b39.JPG)

**Comment by gilbertohasnofb** [comment]
Hi @Maurycy-Sokolowski, I have tested the plane in FG 2016.1.2 and I can't reproduce the problem. Does the problem also happen with other launchers, such as FGRun? 

> copied unzipped directory into $FG_AIRCRAFT as 182s

Did you mean **c**182s?

**Comment by HHS81** [comment]
The file Name should be c182. That means as an example: Aircraft/c182/models/...

I decided to do so,  as we do already have other variants in FGAddon. But that's something that could be discussed.

**Comment by gilbertohasnofb** [comment]
Heiko is of course completely right, and so there was a mistake with my comment above. 

> I decided to do so, as we do already have other variants in FGAddon. But that's something that could be discussed.

Personally I don't see a reason of having keeping the old c182s in FGAddon. As much as the c172p-detailed project has greatly passed the original c172p, the same could be said of the c182s. But that's up to _them_.

**Comment by HHS81** [comment]
Ich don' t mean the existing c182s. We also have a c182rg in FGAddon,  and in of our branch we have a pre-1996 c182-model.

**Comment by gilbertohasnofb** [comment]
Well, the c182rg in FGAddon is clearly another model, but when we release our plane there will be two versions of the S model, one of which is much more developed than the other. I just don't see the point on keeping the other one (FG has already too many barely developed planes in the official repo), but then again the decision is not mine.

**Comment by HHS81** [comment]
Of course we will replace the existing c182s,  if Stuart don' t mind it. But I thought for future ...

**Comment by gilbertohasnofb** [comment]
I see

**Comment by Maurycy-Sokolowski** [comment]
Let me check tonight and I will let you know. The instructions specified c182s which matches the xml files inside the folder so followed that logic.

**Comment by gilbertohasnofb** [comment]
So did you test it again?

> So just to be sure I will rename the folder to c182 and see what happens. 

Yes, that should be it. The folder should be called simply `c182`.

> The version of 2016.1.2 is one I downloaded 1 month ago and installed it after nuking the 2.6 I had for a while. So therein might lie the root of the issue but I checked all the configuration and everything points to the 2016.1.2 $FG_AIRCRAFT directory to retrieve the planes.

If you suspect that might be the case, it could be worth it trying to seek help in the forum. But is our plane the only one which is affecting you?

**Comment by Maurycy-Sokolowski** [comment]
Sorry for the delay... after renaming to c182 it seems to work great! so yes that did fix it.

**Comment by gilbertohasnofb** [comment]
Great, thanks for letting us know!
