### ISSUE TITLE
Remove unneeded liveries (red and blue default)

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#106]
and add the improved black-grey striped Default livery.

**Comment by gilbertohasnofb** [comment]
@HHS81 Do you need a hand with this, Heiko?

**Comment by HHS81** [comment]
@gilbertohasnofb  yep, merge the PR which is ready in a few minutes :smile:

**Comment by gilbertohasnofb** [comment]
Ok!

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/HHS81/c182/pull/113
