### ISSUE TITLE
Add Hobbs meter to the right panel

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#11]
Add Hobbs meter to the right panel (maybe use c172p one, they look quite similar)

**Comment by HHS81** [comment]
Added a branch "instrumentation" containing Hobbs meter from c172p, positioned on hopefully the right spot. Please check before PR

**Comment by HHS81** [comment]
I accidently placed the Hobbs-meter at the wrong spot. There are some C182 S-Variants with the eLT used here, and the Hobbs-meter is just below. Will fix this soon!

**Comment by HHS81** [comment]
Should be fixed now

**Comment by gilbertohasnofb** [comment]
See: https://github.com/HHS81/c182/issues/12#issuecomment-173312375

**Comment by HHS81** [comment]
It seems that the Hobbs-meter we use is a bit too large. I will scale this.
So I close this issue and create a new one.

**Comment by gilbertohasnofb** [comment]
:+1:
