### ISSUE TITLE
Improve heading indicator gauge textures

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#111]
Improve heading indicator gauge textures, as they are in terribly low resolution right now

**Comment by gilbertohasnofb** [comment]
same for NAV1 and NAV2 gauges

**Comment by HHS81** [comment]
I thought about combing those textures into one texture map, which not only decrease RAM-usage, but also enables better lighting effetcs per lightmaps. Negative point about that idea: no reuse possible for other aircraft.

For me is this complete issue a milestone for the next FGAddon Release.

**Comment by gilbertohasnofb** [comment]
Well, given how we currently have individual textures for each gauge I'd say we fix this now (I am already working on it) and later we do as you say and combine into one texture map. Because right now we have three very low res and very ugly looking gauges. And no effort will be loss, since the new textures can be used later on in the texture map. What do you think?

**Comment by gilbertohasnofb** [comment]
Let me know what you think so I can continue to work on it, I was literally doing that right now.

**Comment by HHS81** [comment]
o.k. go on :smile:

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
Better textures are already on branch `Issue-111`:

![fg-0](https://cloud.githubusercontent.com/assets/5700795/16900905/4e6ae446-4c33-11e6-8c44-56dd39d372d1.jpg)

![fg-1](https://cloud.githubusercontent.com/assets/5700795/16900906/4e780612-4c33-11e6-9514-127f9fd134f8.jpg)

But there are two problems with the 3D model for which I need your help:

1) the UV mapping of the knobs of the Heading Indicator is crazy, see how they look like in the image above
2) The knobs themselves do not rotate for some reason

**Comment by HHS81** [comment]
I take a look

**Comment by gilbertohasnofb** [comment]
Thanks! :+1:

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/HHS81/c182/pull/115
