### ISSUE TITLE
Disable/ Hide VNE-decal on the upper left panel

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#112]
Otherwise users will think that the C182 S is able to fly above 18000ft.
This warning decal applies only to Turbocharged C182, since there are able to fly above 18000ft. 

When sometime we decide to make the T C182 T, it can be enabled again.

PR is on the way....

**Comment by gilbertohasnofb** [comment]
My bad, thanks for fixing it.

**Comment by HHS81** [comment]
don't worry, will be usefull sometime later

**Comment by gilbertohasnofb** [comment]
Ok, thanks!

And totally out of topic, but I just checked my spam folder and once again I found your last e-mails to the dev-list there, so it might be other people aren't receiving them either. If I am not mistaken, there were some issues with Yahoo addresses in some of these lists I participate.

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/HHS81/c182/pull/113
