### ISSUE TITLE
Add ELT test gauge to right panel

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#12]
Add ELT test gauge to right panel (panel texture already contains a label ready to be used)

**Comment by HHS81** [comment]
Added a branch "instrumentation" containing ELT test gauge, positioned on the given spot. Please check before PR

**Comment by gilbertohasnofb** [comment]
Okay, I will do so now, also for the Hobbs.

**Comment by gilbertohasnofb** [comment]
The new gauges look good, but I think their position could be reconsidered a bit. First of all, the ELT gauge you used look a bit different than what I have seen before (it looks a bit larger as well):

![elt](https://cloud.githubusercontent.com/assets/5700795/12011758/89ff52dc-acdb-11e5-8684-c327655d9ab1.jpg)

As for the position, we have this image in the POH:

![screenshot from 2015-12-27 20 46 28](https://cloud.githubusercontent.com/assets/5700795/12011760/94b80c5a-acdb-11e5-9e25-407f3604a9f1.png)

Superimposing it in the cockpit, we get:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/12011762/9c8a693c-acdb-11e5-8998-bf417d9eb6f0.png)

**Comment by gilbertohasnofb** [comment]
So if you want to use this ELT test gauge, that's fine with me, but maybe we can reposition them a bit: I think this gauge needs to be a bit lower because it's almost colliding with the top of the panel (where the lamp is), and maybe the Hobbs would look better directly below it.

**Comment by HHS81** [comment]
I used this as reference: http://www.flyperformance.com/wp-content/uploads/2015/05/N182FN-46.jpg but it seems the different ELT was replaced more to the left. I think I will reposition it, so it will be lower and place the Hobbs directly below.

**Comment by gilbertohasnofb** [comment]
> I think I will reposition it, so it will be lower and place the Hobbs directly below.

:+1: Then I will remove the ELT labels from the cockpit texture as your gauge does not need them.

**Comment by HHS81** [comment]
you can keep it, we might still remove the current gauge and add the specific model later. At least for the beginning we have a working ELT.

**Comment by gilbertohasnofb** [comment]
Sounds okay to me.

**Comment by HHS81** [comment]
Oops, I accidently placed it again at the wrong spot.... keep it open until fixed.

**Comment by HHS81** [comment]
will be closed when Hobbs-meter is at the right spot

**Comment by HHS81** [comment]
should be fixed now

**Comment by gilbertohasnofb** [comment]
![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12458401/09c87d14-bfaa-11e5-89fb-ad820b74610a.png)

I think the position of the ELT and Hobbs needs to be rethought a little bit, they colliding with each other and the ELT is colliding with the top of the panel.

**Comment by gilbertohasnofb** [comment]
@HHS81 The position is much better in your last commit, but I still feel that the ELT is too close to the top panel, and also the Hobbs is basically touching the ELT so I think it should be moved slightly downwards.

**Comment by HHS81** [comment]
I can't much mnove it, as the text underneath will appear then.
Anyway, I wouldn't care all too much. I found the page in the POH where the ELT-model is described, and soon as I can I will create the correct model. 
 I close this and create a new Issue.

**Comment by gilbertohasnofb** [comment]
Okay, in that case we just leave as it is, no problems :smiley:
