### ISSUE TITLE
Add ratings to our plane

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#120]
Most planes in FG have ratings for FDM, Systems, Cockpit and Model, and it's up to the creators to decide for the numbers.

I would say that Cockpit is certainly a :star::star::star::star::star:, probably Model as well. For the FDM I would suggest a :star::star::star::star:, similarly to the c172p -- as @onox wrote before:

> Unless the FDM is based on data from actual testing (wind tunnel, etc.), I would say it's (a solid) 4 stars.

As for systems, we still have to implement a lot of them, so it should be a quite lower rating in my opinion. Which is of course not a problem, given that this is a work in progress.

**Comment by gilbertohasnofb** [comment]
See: https://github.com/Juanvvc/c172p-detailed/issues/240

**Comment by HHS81** [comment]
Actually, the c182s fdm uses coefficients from an aerodynamic book, and is tuned to the values given in the POH. So it would be indeed a :star::star::star::star::star:.
But since the engine gives not yet the right numbers at idle, I would stick to four stars.
And I think we should add this to milestone FGAddon Release 1

**Comment by gilbertohasnofb** [comment]
> But since the engine gives not yet the right numbers at idle, I would stick to four stars.

Sounds good, so we keep it at 4 for now, then change it for 5 as soon as the engine is improved.

> And I think we should add this to milestone FGAddon Release 1

Agreed!

And what about the systems, which number should we have? I put 2 stars at the wiki, but I wanted to ask you what do you think.

**Comment by gilbertohasnofb** [comment]
Just let me know about the systems, I will add the ratings and make a PR still today

**Comment by HHS81** [comment]
I think we can keep the ratings, as they are. Systems are not yet quite realistic, so two stars are o.k.

**Comment by gilbertohasnofb** [comment]
:+1:
