### ISSUE TITLE
Default number of passengers

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#129]
The default number of passengers in the payload and weight dialog is 4 -- that is, pilot, copilot and two passengers are weighting more than 0. I think our default should be only the pilot weight, with no copilot nor passengers.

**Comment by HHS81** [comment]
I used this for testing as the POH only uses the MTOW with four passengers. So keep this setting for devel, and one pilot for release

**Comment by gilbertohasnofb** [comment]
> So keep this setting for devel, and one pilot for release

Do we really need to do that? If we are happy with the FDM and we are not testing it, then it's quite annoying to keep two versions of the airplane and it can easily lead to confusion. I would say we can keep one pilot at master, and that's it. If we ever need to test something exhaustively that needs 4 pax, then we can very well set it in the branch that feature is being worked on and remember to remove it before making a PR. What do you say?

**Comment by HHS81** [comment]
I need this setting for further testing, especially when thw work on the engines is going on.

**Comment by gilbertohasnofb** [comment]
But can't you then just use it in the branch you are working on the engine? Do you really need it on the `master` branch?

**Comment by HHS81** [comment]
I need it somewhere. Why we don't comment out the setting I need, and keep the settings for one person in the file just below?

**Comment by gilbertohasnofb** [comment]
That sounds like a plan. I will take care of it.
