### ISSUE TITLE
Add license to repo

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#13]
I believe we should add a license to our repository.

**Comment by gilbertohasnofb** [comment]
@HHS81 I think we never spoke about it, Heiko, but are you up for a GPL license?

**Comment by HHS81** [comment]
Yep, I added just now a GPL V2.0 licence, as I used some things from Stuarts C182 which is under GPL 2.0

**Comment by gilbertohasnofb** [comment]
Perfect.
