### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#134]
The console outputs the following error:

`osgDB ac3d reader: could not find texture "Default.png"`

* * *

Original post:

> I am getting the following error in the console:
> 
> ```
> In file /home/gilberto/WorkingFG/c182/c182/Systems/indicated-airspeed.xml: line 29
>       Property /instrumentation/airspeed-indicator/indicated-speed-kt is already defined.
> In file /home/gilberto/WorkingFG/c182/c182/Systems/indicated-airspeed.xml: line 30
>       Property /sim/model/c182/securing/pitot-cover-visible is already defined.
> Failed to tie property /systems/asi/indicated-airspeed to object methods
> Failed to tie property /systems/asi/pitot-serviceable to object methods
> osgDB ac3d reader: could not find texture "Default.png"
> ```
> 
> Is anyone else able to reproduce it?

**Comment by wlbragg** [comment]
Yes, I have the same errors/warning. I think it is the same thing we discussed on the c172p thread. It can be corrected by defining the associated properties in the -set file instead of the ancillary file.

**Comment by gilbertohasnofb** [comment]
Hmm, I see. Please remind me what was the disadvantage of defining them in the -set file again?

**Comment by HHS81** [comment]
@wlbragg I did, but it didn't went away.

**Comment by wlbragg** [comment]
Did you remove the definition from indicated-airspeed.xml?

@gilbertohasnofb the only downside was the arguments of initializing properties in the file that  uses them. Which I think is not a good enough reason to accept warnings of this kind. Not to mention we define virtually all other properties in the set file.

**Comment by HHS81** [comment]
@wlbragg  I think so

**Comment by wlbragg** [comment]
I'm looking at the code and files right now, one thing I see is a duplicate entry in c182\c182s.xml 

Starting at line 1387

~~~xml
        <system file="c182s-stallhorn"/>
    <system file="propulsion"/>
    <system file="indicated-airspeed"/>    <-------------------
   <system file="c182s-ground-effects"/>    
    <system file="indicated-airspeed"/>    <-------------------
~~~

I went ahead and made a PR.

**Comment by gilbertohasnofb** [comment]
@wlbragg your PR indeed solves the errors in the first 6 lines of my report above, thanks :+1: 

I still get the texture error though: `osgDB ac3d reader: could not find texture "Default.png"`. @HHS81 would you have any idea what's that about?

**Comment by gilbertohasnofb** [comment]
Probably it would make it easier if we try to fix that in the same PR before merging it

**Comment by HHS81** [comment]
@gilbertohasnofb 
That's something new, I have to check which object uses still Default.png and should not

**Comment by gilbertohasnofb** [comment]
Ok, so let's keep this issue opened and I will update the description above
