### ISSUE TITLE
Alt Static Air Knob was missing

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#14]
Added Alt Static Air Knob as 3d model and updated Gimp-Paintkit with. It is in the upper row, first hole.
Important when it comes to icing simulation....

**Comment by gilbertohasnofb** [comment]
Ok, I will add to the PR, so please don't merge it yet. I will fix this and also the rudder pedals.

**Comment by HHS81** [comment]
I'm currently fixing the bugs I introduced and you reported here, I will merge when you give me permission. But what I saw looked really great already!

**Comment by gilbertohasnofb** [comment]
Okay Heiko, great to hear it! So once you have these 3D bugs solved I will then re-adapt the textures and create a new PR, ok?
