### ISSUE TITLE
Correct UV map of three main levers

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#15]
Currently the UV map of the three main levers (throttle, RPM, mixture) look very good, except for the cylinder which "enters" the panel (see below):

![fgfs-screen-005](https://cloud.githubusercontent.com/assets/5700795/12011702/21ffa68e-acd9-11e5-8ed2-b2545ba0d258.png)

I ran a test and I found out their colour are mapped to the centre of the lever "heads", see:

![fgfs-screen-004](https://cloud.githubusercontent.com/assets/5700795/12011705/41c16048-acd9-11e5-9b7d-f47f03215304.png)

Given that we have space on the left side of the flood lamp texture in the panel paintkit, I think we should map these cylinders there. What do you think, @HHS81?

**Comment by HHS81** [comment]
yep, should be possible.

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by HHS81** [comment]
Done
