### ISSUE TITLE
UV map of some circuit breakers could be better

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#16]
UV map of some circuit breakers could be better. Some of them are lacking any texture on the top of the hexagon where they sit, see:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12011726/db26b9e0-acd9-11e5-9a3f-cd2a264cdbfd.png)

**Comment by HHS81** [comment]
Fixed. Not lack of textures, but sinply the text was to close to the circuit breakers. Fixed by shifting the uvmap edge of the circuit breakers a bit down so it won't interfere with the text.

**Comment by gilbertohasnofb** [comment]
Seems like this bug has been re-introduced:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/12407159/cd952794-be54-11e5-9874-45e187102134.png)

**Comment by HHS81** [comment]
Ah, yes, I see.

**Comment by HHS81** [comment]
should be fixed now

**Comment by gilbertohasnofb** [comment]
Confirmed, thanks! :+1:
