### ISSUE TITLE
Recalculate light angles in the animation

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#17]
https://github.com/HHS81/c182/issues/4#issuecomment-167439640:

> Just tested it and they look very good IMO, I think we can close this issue. But I found another strange thing with the lights: from shallow angles, the wingtip lights grow in size. Is this a side effect of having them fade out according to the angle? See:

![](https://cloud.githubusercontent.com/assets/5700795/12011848/286eaf9a-ace0-11e5-8a8e-c26c7928d465.png)

Heiko wrote:

> Ah, thanks for the reminder. I have to recalculate the angles in the animation, was on my to-do-list just before I headed back to home.

**Comment by HHS81** [comment]
Fixed
