### ISSUE TITLE
"holes" in the 3D model of the seats

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#19]
There are some "holes" in the 3D model of the seats, see:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12024790/28ce38b6-ada8-11e5-9c53-d3cab20496b6.png)

**Comment by gilbertohasnofb** [comment]
Possibly related to https://github.com/HHS81/c182/issues/18

**Comment by HHS81** [comment]
Here in the blend-file I can't see any holes, but a not so clean made mesh. The back row doesn't show this. So maybe I should use and adapt the back row for the front row.

**Comment by gilbertohasnofb** [comment]
Will this influence the current UV mapping? If so, please let me know so I freeze the work on the seats until this is fixed.

**Comment by HHS81** [comment]
Only the head-rest seems to be different. But better freeze it, maybe I can map it better, so you have it more easy.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by HHS81** [comment]
Fixed.
