### ISSUE TITLE
re-UV-map rudder pedals 

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#2]
Re-UV-map rudder pedals as they are not in the same size in the texture file

**Comment by gilbertohasnofb** [comment]
We can check this out once I push the textures as it will make this much easier I suppose. Just give me a couple of days.

**Comment by HHS81** [comment]
Fixed Issue #2

**Comment by HHS81** [comment]
Hi,

did a mistake with the pedals uvmapping, I remapped them to indentical size, but i didn't use your texture as reference. I will fix this.
The Alt Static Air Knob is uvmapped, it just needs a red knob texture. All other things will not be influenced in any way.

**Comment by gilbertohasnofb** [comment]
> I will fix this.

If you want, I can do it myself, since I will make corrections to the textures anyway. So don't bother :wink: 

> The Alt Static Air Knob is uvmapped, it just needs a red knob texture. All other things will not be influenced in any way.

:+1:

**Comment by HHS81** [comment]
I fixed it now to your layout, it was easier for me than I think it will be for you. And I was responsible for the mess.... ;-)

**Comment by gilbertohasnofb** [comment]
hehehe thanks then, Heiko!
