### ISSUE TITLE
Improve seat frames

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#20]
From https://github.com/HHS81/c182/issues/18#issuecomment-167661607:

> As for the reference for the seat frame, I have this picture here (not sure if it is from your zip or if I got somewhere else on the internet):
> 
> ![n67mr_15](https://cloud.githubusercontent.com/assets/5700795/12025723/ecfeae9c-adb1-11e5-9780-c3f741797432.jpg)
> 
> Else we can use something generic like the c172p, which is already better than a simple rectangle. In the texture below, the seat frame is in the bottom right, and its left side is what touchs the ground:
> 
> ![](https://raw.githubusercontent.com/Juanvvc/c172p-detailed/master/Models/interior.png)
> 
> What do you say?

@HHS81 wrote:

> After a long research I don't finy any reference images. So I will use the one from the C172p.

**Comment by HHS81** [comment]
improved seat frame, though the model from the c172 had been heavily adapted due to a different, more modern seat used in the c182

**Comment by gilbertohasnofb** [comment]
I think our seat mounts are upside down, actually! See: https://github.com/Juanvvc/c172p-detailed/issues/633#issuecomment-173036122

**Comment by HHS81** [comment]
Indeed, ouch!  Now I understand why I had to heavily adapt it.....Well, easy to fix, I don't think there is a change on the UVMap needed.
