### ISSUE TITLE
Major bug: Wrong aircraft dimensions!!!

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#23]
The original C182 -Q has a length of 28ft, the later ones (S-T) has about 29ft. But we model the S-T Variant.

Issue:
1.) The current 3d-model has the shorter nose of the old variants.
2.) The current 3d-model has 1.1161 x larger wing span than it should have and pobably chord as well
3.) The current 3d-model has 1.1161 x larger length than it should have 
4.) The current 3d-model has 1.0989 x higher than it should
4.) The current 3d-H-stab has at least the correct size!
5.) Panel dimensions are at least correct!

Conclusion: while proportions is mostly equal, the whole scale of the exterior model and cabin model is larger than it should be. Panel size is correct, H-Stab as well. That means to correct the dimensions and extent the aircraft nose. That means that the UVmap of the exterior model has to be corrected, and with that the paintkit as well. 

Procedere:
1.) correct aircraft length (X-scale), increase nose length 
2.) reduce wing span (Y-scale)
3.) correct height (Z-Scale)
3.) adapt exterior UVMap and create new Paintkit
4.) adapt normalmap
5.) adapt animation of exterior surfaces....(doors, flaps, ailerons.....)
6.) correct main gear size

Interior UVMap will not be influenced, as the proportions are more or less equal

**Comment by gilbertohasnofb** [comment]
Nice one spotting this!

> That means that the UVmap of the exterior model has to be corrected, and with that the paintkit as well. 
> [...]
> Interior UVMap will not be influenced, as the proportions are more or less equal 

Okay, I didn't even start working on any liveries yet and probably I won't be able to do so in the next days anyway, so take your time with this one. Also, while you are taking a look on the external model, maybe you want to check this issue out as well: https://github.com/HHS81/c182/issues/24

**Comment by HHS81** [comment]
Oh and the span of the main gear is at least correct as well....

**Comment by HHS81** [comment]
Procedere:
4.) adapt animation of exterior surfaces....(doors, flaps, ailerons.....)

**Comment by HHS81** [comment]
Hi,

Yep, took accidently a detailed blueprint of the older C182. I noticed  
tody that the older C182 looks different than newer one and checked the  
dimensions given in the POH.

New uvmapping and especially creating the paintkit will need a while. Most  
of the corrections of the scale are mostly done, need to reduce wing span  
and correct engine nose.

Damn, I hoped I was done with exterior stuff.....
Can't say how long I will need but I will try as fast as possible.

Sorry
Heiko


>
> Nice one spotting this!
>>
>> That means that the UVmap of the exterior model has to be corrected,  
>> and with that the paintkit as well.[...]
>> Interior UVMap will not be influenced, as the proportions are more or  
>> less equal
>
> Okay, I didn't even start working on any liveries yet and probably I  
> won't be able to do so in the next days anyway, so take your time with  
> this one. Also, >while you are taking a look on the external model,  
> maybe you want to check this issue out as well: #24
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Erstellt mit Operas E-Mail-Modul: http://www.opera.com/mail/

**Comment by HHS81** [comment]
Procedere:
5.) correct main gear size

**Comment by gilbertohasnofb** [comment]
> Damn, I hoped I was done with exterior stuff..... Can't say how long I will need but I will try as fast as possible.

Heiko, there is no rush, really, take your time with it. I will be travelling a lot in the next days so I probably won't be able to work much.

But if I may make a personal request, the only issue that is really holding me from pushing all the textures is #15, which should be quite simple to solve. Do you think you could take a look at it when you have time? Then I can push all the interior textures and we can tackle those other UV-mapping related issues later.

**Comment by HHS81** [comment]
Exterior model is ready and even refined compared with before, animated (flight control surfaces, Cowl Flaps, doors, windows ...), fixed the tranparency issue of the prop, fixed the navlight issue. I have started with a blank livery and a normalmap- will need some time though.
![fgfs-screen-001](https://cloud.githubusercontent.com/assets/12649375/12102868/3880ee52-b33e-11e5-93e9-c5c6106ab301.jpg)
![fgfs-screen-002](https://cloud.githubusercontent.com/assets/12649375/12102869/38853c1e-b33e-11e5-98f1-221242a70116.jpg)
![fgfs-screen-003](https://cloud.githubusercontent.com/assets/12649375/12102870/3886ada6-b33e-11e5-965e-f7ad0065ea42.jpg)

**Comment by gilbertohasnofb** [comment]
Looks great!

>The longer and different shape of the C182 S and T-model was a pain, and looks different to the older version I accidently modelled. But I think it looks like a C182 S variant.

I dont understand, you mean the new model looks like a variant rather than the real thing? In which sense, what are the differences?

**Comment by HHS81** [comment]
Well, it looks different to the older C182 Variants, i accidently modelled. I was rather used already to its look, so yesterday I was uncertain. But comparing again I think I have done everything right. I hope tu upload it this week.

**Comment by gilbertohasnofb** [comment]
I understand now. Well, the new model looks great, cant wait to try it out :smiley:

**Comment by HHS81** [comment]
Progress:
![fgfs-screen-013](https://cloud.githubusercontent.com/assets/12649375/12214235/f82d9cd2-b68b-11e5-9629-6b17d3c608d7.jpg)
![fgfs-screen-012](https://cloud.githubusercontent.com/assets/12649375/12214233/f82ced6e-b68b-11e5-8667-69edcc6fe377.jpg)
![fgfs-screen-016](https://cloud.githubusercontent.com/assets/12649375/12214234/f82d9944-b68b-11e5-9600-16c257a5710c.jpg)

**Comment by gilbertohasnofb** [comment]
Looks amazing!!

**Comment by HHS81** [comment]
Fixed, and keeping the old model in the "Classic"- Branch, so one time the old variants can be made of it.
