### ISSUE TITLE
better UV-map of liveries on nose and tail

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#24]
Better UV-map of liveries on nose and tail, see how they do not match perfectly:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12043278/dfff214a-ae83-11e5-85e1-fb4663f75082.png)

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/12043277/dffea3aa-ae83-11e5-86ab-426b304e8536.png)

There might be an issue as well in the tail part of the fuselage (where the light is in the second picture above) but we can't tell because these liveries don't have any special details there to make it recognizable.

**Comment by HHS81** [comment]
No, UVMap is correct - you can check this by using "Default.png" as livery. It is just my bad painting expertise.....
![Uploading UVMapExteriorIsCorrect.jpg…]()

**Comment by HHS81** [comment]
![uvmapexterioriscorrect](https://cloud.githubusercontent.com/assets/12649375/12043410/356beeb4-ae85-11e5-90dd-f8dad11f33c9.jpg)

**Comment by gilbertohasnofb** [comment]
Okay then, Heiko!

**Comment by gilbertohasnofb** [comment]
@HHS81 You closed and reopened this issue twice, did you mean the leave it open? I think after what you explained above it should be closed, right?

**Comment by HHS81** [comment]
Yep, wanted to close it, but was faster than the upload of the image. So I reopened it....

**Comment by gilbertohasnofb** [comment]
If you reopened it just to upload the image, then you could have just posted the image in the closed issue since a closed issue is still able to receive comments. But no worries :smile:
