### ISSUE TITLE
Apply new texture to flap lever

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#26]
I created a new texture for the flap lever:

![flaps](https://cloud.githubusercontent.com/assets/5700795/12060080/190bfb40-af68-11e5-99de-690c4ee1a863.png)

This has already been pushed to a branch named `improved-instruments`, together with a better AI. Could you please apply the texture to the lever using that branch? Then we can merge it to the master.

**Comment by HHS81** [comment]
Done
