### ISSUE TITLE
FDM uses wrong type of fuel --> wrong weight of fuel

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#27]
According http://wiki.flightgear.org/JSBSim_Fuel_System JSBSim calculates 6.6 lbs/ gal fuel weight as standard. This is the density of Jet Fuel. 
But the C182S uses AvGas. So it should be 6.02lbs/ gal. So fuel weight is not correct!

Fix is under way 
as the fdm has been already updated on my system to match the new exterior model 
(also this fdm  already enhanced by using real stability derviates values; and pointmass locations from POH. Matches real weight and balance calculators up to 99%!)

**Comment by gilbertohasnofb** [comment]
:+1: Nicely spot!

**Comment by HHS81** [comment]
Thanks: was playing with a Weight and Balance calculator, when I noticed that the weights are not matching. I guess some other JSBSim aircraft has this bug as well....

**Comment by gilbertohasnofb** [comment]
Maybe it would be nice to write to the mailing list about it so other aircraft maintainers can know about this bug.

**Comment by HHS81** [comment]
I'm not sure if the mailing-list is the right place. There are not many airctaft-developers. Most of them are in the forum, or anywhere else....

**Comment by HHS81** [comment]
Fixed, and made use of the JSBSim fuel tank features.....
