### ISSUE TITLE
Spinning propeller blades look worse than before

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#3]
Spinning propeller blades went from having a round contour and being textured to being simple untextured triangles, see before and after:

![](https://camo.githubusercontent.com/f3a943bc62726b357aca1eda9d60c67e60587f72/687474703a2f2f61626c6f61642e64652f696d672f666766732d73637265656e2d30313435797568672e6a7067)

![](http://s24.postimg.org/xa2khh6hx/fgfs_screen_007.png)

**Comment by HHS81** [comment]
yep, it is a regression, and will be replaced with a better animation soon.

**Comment by HHS81** [comment]
Created a new blurredprop, but issues with z-fighting with windshield. Probably not fixable due the nature of blend-animation and shader-effect.

**Comment by HHS81** [comment]
![fgfs-screen-001](https://cloud.githubusercontent.com/assets/12649375/12011821/3184dac4-acdf-11e5-9be7-66a2b538cd7c.jpg)

**Comment by gilbertohasnofb** [comment]
Yes, I just tested it and it looks pretty good!

>  issues with z-fighting with windshield

I can't reproduce that, here it looks fine.

**Comment by HHS81** [comment]
Hmmm... strange looking through the prop towards the windhield from outside let the windshield disappear (as in the image above)....

**Comment by gilbertohasnofb** [comment]
Wait, I will test that again.

**Comment by gilbertohasnofb** [comment]
Hmm, I take it back, the problem is there indeed. But I don't think this can be considered as a z-fighting as the prop and the windshield do not share the same z position. Would you like me to ask the c172p team if they know what might be going on? The prop blur in that plane isn't causing any troubles I believe.

**Comment by HHS81** [comment]
yes, why not.

**Comment by gilbertohasnofb** [comment]
Ok, I will do that.

**Comment by wlbragg** [comment]
What aircraft is this?
https://camo.githubusercontent.com/f3a943bc62726b357aca1eda9d60c67e60587f72/687474703a2f2f61626c6f61642e64652f696d672f666766732d73637265656e2d30313435797568672e6a7067
Did you use it's propeller cod and model for the one that isn't working right?

**Comment by HHS81** [comment]
@wlbragg: its the same aircraft we just talk about - Cessna 182S.
Animation code is the same, I just changed the blurredprop model and the texture. I know that the problem was the same with this. I guess the alpha-blend animation is not compatible with the shaders. I have the same problem on the EC 135 P2.

**Comment by gilbertohasnofb** [comment]
@wlbragg it seems @HHS81 has fixed this according to https://github.com/HHS81/c182/issues/23#issuecomment-168837220. Thanks for having a look at it though!

**Comment by HHS81** [comment]
The issue had a simple reason: mismtached object name, so transparent.eff coulden't apply. This issue will be closed when the master branch has been updated. 
And from me as well: @wlbragg: Thanks for looking at!

**Comment by HHS81** [comment]
Fixed
