### ISSUE TITLE
Holes in the doors

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#31]
There are holes in both doors, see:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12407131/8d130d4e-be54-11e5-8fb7-dce657b1c45f.png)

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/12407143/b018e2d2-be54-11e5-9df1-3788653a64ea.png)

On the bright side, there will be extra ventilation in the cabin :smile:

**Comment by HHS81** [comment]
Take a look what happened.

**Comment by HHS81** [comment]
should be fixed

**Comment by gilbertohasnofb** [comment]
Yep, it's fixed now, thanks a lot!
