### ISSUE TITLE
dome lights texture are too large

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#34]
dome lights texture are too large

**Comment by gilbertohasnofb** [comment]
Just so I don't forget about this in the future.

**Comment by gilbertohasnofb** [comment]
Done.

**Comment by HHS81** [comment]
Sorry, not really improvment. I know the uvmapping can a bit confusing. I took a look into the Gimp file and I'm sure I can fix this.

**Comment by gilbertohasnofb** [comment]
Maybe I am misunderstanding how those dome lights are supposed to look, so feel free to fix them :smile:

**Comment by HHS81** [comment]
Fixed:
![fgfs-screen-003](https://cloud.githubusercontent.com/assets/12649375/12687524/bc141186-c6d0-11e5-975c-e342a3614f6c.jpg)

**Comment by gilbertohasnofb** [comment]
Perfect! :+1: I will work on a texture for it soon
