### ISSUE TITLE
Tachometer should be smaller

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#36]
Tachometer should be smaller, see how the gauge ticks are almost not visible:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/12458461/50b843d0-bfaa-11e5-98a8-1e704993128d.png)

**Comment by HHS81** [comment]
Is on my To-Do-List together with other instrument textures already....

**Comment by HHS81** [comment]
Fixed

**Comment by gilbertohasnofb** [comment]
Perfect. But I just noted that the altimeter also needs some scaling, should I open a new issue for it?
