### ISSUE TITLE
Some parts of the pedals are coloured in funny colours

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#37]
Some parts of the pedals are coloured in funny colours, see:

![fgfs-screen-004](https://cloud.githubusercontent.com/assets/5700795/12458536/956a81b4-bfaa-11e5-8b82-d52a0913b9f2.png)

(the circles are in the colours which are visible in the cockpit)

All these little parts can be simply assigned as pure black in Blender so we don't have to fuss with textures and UV mapping.

**Comment by HHS81** [comment]
-keep the number of materials used as low as possible for better computer perfomance
-I will look at uvmapping, which is actually the reason behind

**Comment by gilbertohasnofb** [comment]
Okay :+1: . Probably the side of the pedals can be mapped using the same texture as the pedal levers (the cylinders that connect it to the floor), and it seems that only the left cylinders have the back untexturized. As for the blue line close to the fuel selector, probably the UV map isn't taking the whole object.

**Comment by HHS81** [comment]
should be fixed - suffered from the translation in the UVmap

**Comment by gilbertohasnofb** [comment]
The pedals look perfect, but the blue line on the side of the fuel selector is still there:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12462920/21edbd2a-bfc1-11e5-987b-d35fc0c9ca80.png)

**Comment by HHS81** [comment]
fixed

**Comment by gilbertohasnofb** [comment]
confirmed :+1:
