### ISSUE TITLE
Create speaker on the ceiling

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#38]
Create speaker on the ceiling, see:

![dscn1882_sp](https://cloud.githubusercontent.com/assets/5700795/12484409/7ec0ca08-c05a-11e5-8cbd-71d6cc2b6645.JPG)

**Comment by gilbertohasnofb** [comment]
I had previously done it via textures alone, but it doesn't look that good like that. Would it be possible to do it by adapting the 3D model and then applying the texture? I think we still have space on `PanelTexturing-Interior.png` to add a small circle (for instance, above the seat belts in the middle of the texture). Let me know what you think.

**Comment by HHS81** [comment]
It seems to me the speaker is a bit recessed. I have to look if I can do this without all too much effort, and see where I put the speaker on the UVmap.
Unfortunately my laptop needs a 5hr maintenance of the harddrive, and I still have a last term-paper/ essay open with a very near deadline before finally having sucessfully passed all my exams. (I got my  resultat of bachelor thesis yesterday :-))
So it won't happen this weekend, but probably next week.

**Comment by gilbertohasnofb** [comment]
> finally having sucessfully passed all my exams

Congratulations, Heiko! :tada: :smile: :+1: Very happy for you.

> So it won't happen this weekend, but probably next week. 

No rush at all, I am also quite busy with my thesis myself 

Indeed the speak is a bit recessed, so it would change the mesh on that place a bit. Anyway, have a look at it when you have time and make a decision about it, okay?

**Comment by HHS81** [comment]
Not yet passed! 
But soon when I have finished my last exam in form of term-paper/ essay... 
But thanks anyway! :smiley:

**Comment by gilbertohasnofb** [comment]
Oh, I totally misunderstood you :blush: So save the champagne and good luck with the paper!

**Comment by HHS81** [comment]
I hope it looks nice now:
![fgfs-screen-003](https://cloud.githubusercontent.com/assets/12649375/12687516/ac70830e-c6d0-11e5-9b32-bb0e0669de8f.jpg)

**Comment by gilbertohasnofb** [comment]
Perfect! :+1: I will work on a texture for it soon
