### ISSUE TITLE
Reposition some of the lights

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#4]
Some of the lights must be repositioned:

- the landing lights in the right wing should be moved a bit backwards (towards the tail)
- the wing tip lights on both sides should be moved a bit backwards and a tiny bit upwards as well (see reference below)
- strobe lights may need to be moved a bit upwards as well

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12006881/bb4e3328-abe9-11e5-8a82-3fa33d1a19e3.png)

Compare the wing lights to this:

![](https://preciseflight.com/resources/img/products/cessna_wingtips_!570x328.jpg)

**Comment by HHS81** [comment]
I used this: http://www.airmart.com/sites/default/files/styles/slideshow-full/public/Left%20in%20front%20of%20wing%20low%20N9570A.jpg?itok=BbJLl63G as reference (showing a C182S ), but indeed my lights seems not to be at the right position.

**Comment by gilbertohasnofb** [comment]
You are right, the S model has lights as you shown in that image. Here is another one from www.airliners.net :

![](http://cdn-www.airliners.net/aviation-photos/photos/8/3/8/2740838.jpg)

I think the angle in the image I first posted may give the impression they are too much to the back.

**Comment by HHS81** [comment]
I repositioned landing and taxilights more backwards toward the wing. I also fixed the beacon light position. Not sure yet about the wing tip lights

**Comment by gilbertohasnofb** [comment]
> Not sure yet about the wing tip lights

IMO, they should be a tad bit higher, but it's up to you, they look very close to the reference images.

**Comment by gilbertohasnofb** [comment]
Just tested it and they look very good IMO, I think we can close this issue. But I found another strange thing with the lights: from shallow angles, the wingtip lights grow in size. Is this a side effect of having them fade out according to the angle? See:

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/12011848/286eaf9a-ace0-11e5-8a8e-c26c7928d465.png)

**Comment by HHS81** [comment]
Ah, thanks for the reminder. I have to recalculate the angles in the animation, was on my to-do-list just before I headed back to home.

**Comment by gilbertohasnofb** [comment]
I will create a new issue for it then so we can close this one once you are happy with the positions.

**Comment by HHS81** [comment]
Fixed
