### ISSUE TITLE
3D bug in the top left corner of the cockpit

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#42]
3D bug in the top left corner of the cockpit:

![fg-0](https://cloud.githubusercontent.com/assets/5700795/12687962/6381ce7a-c6d3-11e5-83f5-3051dcc31fa6.jpg)

![fg-1](https://cloud.githubusercontent.com/assets/5700795/12687966/685dd61e-c6d3-11e5-97f9-b4db4fe5025e.jpg)

**Comment by HHS81** [comment]
yep, noticed already, no idea yet whats wrong

**Comment by gilbertohasnofb** [comment]
ok

**Comment by HHS81** [comment]
fixed

**Comment by gilbertohasnofb** [comment]
:+1:
