### ISSUE TITLE
Adding AOMaps on interior textures?

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#46]
Should we add AOMaps on the interior-textures?
The mainpanel as an example get then some some touch like Carenado Aircraft:
![image](https://cloud.githubusercontent.com/assets/12649375/12699346/451d42ee-c7b8-11e5-95c8-fb9e141ae479.png)

Ours with 80% Opacity of AOMap (can be increased, and the whole AOMap improved by changing settings wihile generating the AOMap in Blender)
![fgfs-screen-005](https://cloud.githubusercontent.com/assets/12649375/12699423/b039a070-c7ba-11e5-8a22-0a50399bb08f.jpg)

See  AOMaps-branch

**Comment by gilbertohasnofb** [comment]
Sorry Heiko but what is an AOMap and what does it do? Nevertheless, that shot of yours look stunning!

**Comment by HHS81** [comment]
AO stands for Ambient occlusion: https://en.wikipedia.org/wiki/Ambient_occlusion

Though this is not quite right, then what I did and plan is more or less ambient shadows generated by Global Illumination (which actually will not conflict with Rembrandt shadows or the ALS shadows). 

I will see if I can enhance this more, so we can close to those commercial products (As much as I know some Carenado-devs uses Blender for their work....)

**Comment by gilbertohasnofb** [comment]
I see, that looks really interesting!

**Comment by gilbertohasnofb** [comment]
It seems that the files `dev/AOPanel.png` and `dev/AOMap.png` have wrong proportions (both are 2048x2048 while the panel and livery files aren't). I guess this won't affect anything, but for instance the AOPanel is twice the size it should be.

**Comment by HHS81** [comment]
I know, it happens when I create them in Blender. Those files went accidently in the wrong branch and aren't to be considered ready to use.

**Comment by gilbertohasnofb** [comment]
@HHS81 in the c172p, @wlbragg has implemented the irradiance effect which looks really good and may be related to this, since it drastically reduces the brightness of the cockpit in general when the sun isn't directly shinning upon a surface.

Also, the same effect can be used to generate some irradiance from the instrument lightning and radio digits, see: https://www.youtube.com/watch?v=o4zyCCea7Nw

And these are the PR where the effect has been implemented:
https://github.com/Juanvvc/c172p-detailed/pull/730
https://github.com/Juanvvc/c172p-detailed/pull/731

**Comment by wlbragg** [comment]
@HHS81 is this just taking your normal texture (like you existing panel texture) and running it through some kind of filter in GIMP to add the shadows to the textures? In other words, it has nothing to do with an ALS or any of FG's generated effects, it's just editing the texture sheets to look way better?

**Comment by gilbertohasnofb** [comment]
@wlbragg if I am not mistaken, you create these AOMaps in Blender. If you are interested, open the paintkit `GimpPaintkit.xcf` from https://github.com/HHS81/c182-Textures/tree/master/Liveries and see the layer named AOMap.

**Comment by wlbragg** [comment]
That is really impressive, but in a sim environment that is supposed to be providing the light for shading the shaded areas of the aircraft how is that going to look, say with the sun on the horizon? Isn't the lighting on the skin then going to be wrong? I suppose it is subtle enough that is still looks better than without it, as  in it still fools the eyes and brain to see the depth.?

**Comment by HHS81** [comment]
Too strong effect? 

(non-edited, just for testing - no promo)
![giao_test](https://cloud.githubusercontent.com/assets/12649375/14802474/510e37c0-0b51-11e6-8c6b-9cd39bda5007.jpg)

**Comment by gilbertohasnofb** [comment]
I don't think it's too strong, I quite like the shot above!

**Comment by HHS81** [comment]
@gilbertohasnofb  can be closed?

**Comment by gilbertohasnofb** [comment]
Sure, I forgot about it!
