### ISSUE TITLE
create missing engine instruments

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#47]
create the missing engine instruments, so whole bird can pushed to FGAddon.
I think setting the missing instruments as milestone for FGAddon should be o.k.?

**Comment by gilbertohasnofb** [comment]
I think if the cockpit has all instruments and the main knobs and switches are clickable, then I also think it would be time for a first merge to FGAddon. Also, when that happens, I will announce the plane in the wiki newsletter.

**Comment by HHS81** [comment]
Done

**Comment by gilbertohasnofb** [comment]
Looks really good, Heiko! :+1: But for some reason the vertical speed indicator isn't showing to me any longer.

**Comment by gilbertohasnofb** [comment]
I get the error `Failed to load file: "Aircraft/c182/Models/Instruments/vsi.xml"`

**Comment by gilbertohasnofb** [comment]
Found the problem, it's the capitalization of the `VSI.xml` file (Linux is case sensitive). I will fix it myself now.
