### ISSUE TITLE
replace thumbnail and create splash screen(s)

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#49]
I think we must replace thumbnail and create new splash screen(s)

**Comment by gilbertohasnofb** [comment]
@HHS81 would you like to use the same style of splash screen as the c172p? If so, I can copy the template to https://github.com/HHS81/c182-Textures/ so we can work on some splash screens

**Comment by HHS81** [comment]
Yep, I like your splash screens a lot! If you want to make some, I would be very delighted!

**Comment by gilbertohasnofb** [comment]
Thanks, I am happy you like those! So as soon as we have the engine instruments in the cockpit as well as some new liveries I will create a bunch of splash screens

**Comment by gilbertohasnofb** [comment]
I added the FGAddon Release milestone (which by the way, has a small typo, it's missing the "a" in "release"). I think we can at least have a cockpit image as thumbnail and splash screen for now, and then later I will create some nice different splash screens.

**Comment by gilbertohasnofb** [comment]
By the way, Heiko, I have seen that you uploaded some great shots (as always) to the repository page, but I noticed that you left the frame rate counter on them. If you plan to make shots for promotion (splash screen, repo page, forum, etc.), would you mind hiding those? I will make some "GIMP surgery" on them to hide the fps and update the `README.md` with the new links, then I will add these images to the forum page. Is that all right with you?

**Comment by gilbertohasnofb** [comment]
I hope you don't mind but I just went ahead and did the surgery :smile:

**Comment by HHS81** [comment]
Sure no problem. I left the fps counter as control for myself.

**Comment by gilbertohasnofb** [comment]
:+1:
