### ISSUE TITLE
RPM and mixture levers aren't visible

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#5]
RPM and mixture levers aren't visible, they are "inside" the cockpit and should be moved backwards (towards the pilot)

**Comment by HHS81** [comment]
That's strange. I know I changed the position of those in the 3d-model a bit, but this should never break the animation. I'll investigate just right now.

**Comment by gilbertohasnofb** [comment]
It looks to me that what happened is that you tried to set the minimal position of the mixture level model while the mixture was fully rich. Same for the RPM.

**Comment by HHS81** [comment]
Found it: I placed both lever in full position assuming, that pitch and mixture is always in full position. They are not, FGFS puts them in into full-position after loading the -set.xml file. So it is fixed now!

**Comment by gilbertohasnofb** [comment]
:+1:
