### ISSUE TITLE
create new liveries

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#51]
Create some new new liveries for the plane

**Comment by gilbertohasnofb** [comment]
@HHS81 do you still plan to do some "big" work on the exterior model or on the paintkit, or can I start having fun with the exterior model? :smile:

**Comment by HHS81** [comment]
Thanks for the reminder!

Some lines are still missing, and some rivets. 
And a small enhancement to the doors. 

Hope today I have it ready

**Comment by gilbertohasnofb** [comment]
Okay, so once this is done I will create some liveries for us :+1:

**Comment by HHS81** [comment]
didn't made it today, engine instrumemtes needed too much time

**Comment by gilbertohasnofb** [comment]
No problems at all, there is no rush.

**Comment by gilbertohasnofb** [comment]
Heiko, I am closing this since we have already a nice number of liveries (which doesn't mean we can't add more later).
