### ISSUE TITLE
Missing paintkit

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#54]
Paintkit still missing - should be done asap

**Comment by HHS81** [comment]
See: https://github.com/HHS81/c182-Textures/liveries for paintkit

when usuable, it can be copied into an own folder c182/Models/Paintkit or anywhere else

**Comment by gilbertohasnofb** [comment]
> when usuable, it can be copied into an own folder c182/Models/Paintkit or anywhere else

I don't think I understand, Heiko, is this still a work in progress and the message above is a reminder to yourself or is the paintkit done in principle?

**Comment by HHS81** [comment]
It was late ( better: very early) when I wrote this comment.
I have paintkit ready for Gimp and Inkscape, and put it into c182-textures-repo.
I'm sure you wanna test ist, and report things which might be a problem. 

I thought about adding into the mentioned folder. But I think this would increase file size, and we have an official livery database with palce for paintkits as well. 

Let me know what you think.

**Comment by gilbertohasnofb** [comment]
Great, Heiko! I will get my hands on it and make some liveries for us then :smile: 

> I thought about adding into the mentioned folder. But I think this would increase file size, and we have an official livery database with palce for paintkits as well. 

Yeah, I agree with you on this, let's leave it in the separate repository for now.

**Comment by gilbertohasnofb** [comment]
Heiko, I started working on some liveries. I have to say your paintkit is simply the best paintkit I have ever encountered, it's been such a pleasure to work with it! :smile: :+1: :clap:

I am creating a PR for my first livery now

**Comment by HHS81** [comment]
:blush:
Thanks!

**Comment by HHS81** [comment]
Should I now add the paintkits so users have them easily, or keep them out?
So when  released to FGAddon we can send them ro Livery database?

**Comment by gilbertohasnofb** [comment]
I would probably keep all xcf in the `c182-Textures` repository, but I don't have a strong opinion about it

**Comment by gilbertohasnofb** [comment]
Also, we can probably close this issue here I think

**Comment by gilbertohasnofb** [comment]
Hi Heiko, I just wanted to give you some more feedback on the paintkit. As I said, your work is really excellent (the best I have seen in FG), but there are some minor things that you could have done to improve it. I am not proposing to change anything at all (particularly now that we have so many liveries already!), I am just giving you some feedback so you can create even better paintkits in your next projects. The few comments I have are:

- It's really good that you made the fuselage left and right sides inverted in the paintkit, but unfortunately they are not precisely at the same distance from the margins. This means that if you create a layer of paint for one side of the fuselage, then duplicate it and mirror it vertically, it will not precisely fit the other fuselage, and so it become a matter of trial and error of adjusting it perfectly to the correct position. If the top fuselage was `x` pixels from the top margin and the bottom fuselage was also `x` pixels from the bottom margin, this would be trivial, and save a lot of work. 

- when UV mapping it's really important to keep the same proportions all over the place for similar objects. I have the impression that, for instance, there may be some tiny differences between some similar objects, such as the top and bottom horizontal stabilizers.

- sometimes a detailed breakdown of every single face of an object isn't really necessary. See for instance the fuel selector switch in the main panel, you broke it down in 18 faces, but a simple top view would have sufficed since the object is mainly white in the sim.

**Comment by HHS81** [comment]
Yes, you were much faster as I ever thought, incredible, and many thanks for! :+1: 

> ...If the top fuselage was x pixels from the top margin and the bottom fuselage was also x pixels from the bottom margin, this would be trivial, and save a lot of work.

The uvmap is made like this, so no space is wasted, using much space as possible, and leaving much space as possible for other parts of the model. This is done to provide and support highly defined textures (if possible!). We speak of pixel per meter ratio. The more pixel per meter the better. For this model I get an approx. ratio of about 280, the Carenado Ct182T Payware has 350 but seems much more difficult but possible to paint, as we can see here: 
![e1](https://cloud.githubusercontent.com/assets/12649375/13085944/0e30566e-d4e1-11e5-98e0-242fed24e3f5.jpg)

Because there are a lot of objects and faces to uvmap, they have to distributed in a most intelligent way on the existing space - that's why it can't be made sure that they are placed symmetric within the margins. As much as I know Gimp and I have used it a lot in the past, you can select parts easily, copy them, mirror it and paste it. And the guide-lines assist a lot to position it. That's how I corrected the AOMap - I just rendered the spinner, cut it out and copied,  deleted the old buggy one, and pasted the one in there, 

> ...I have the impression that, for instance, there may be some tiny differences between some similar objects, such as the top and bottom horizontal stabilizers.

I have checked it, and both has absolutely the same size and proportions. The main wing has indeed some issues, but had never been intended and had been fixable if reported. 

>... down in 18 faces, but a simple top view would have sufficed

Not when you plan to use AOMaps and Lightmaps....

> ... in your next projects

Thanks for your feedback, if possible I will consider it in the future. Unfortunately there won't be next projects when things will go well and I can finance my Master degree course, which would start in some few weeks. And even if not - the work on the Cessna 182 consumes a lot of time for me already, and I only see new issues to fix. We provide payware quality without beeing payed for. So I feel more and more tired....

**Comment by gilbertohasnofb** [comment]
Heiko, I hope you didn't get me wrong with those suggestions; as I had written earlier, this paintkit of yours is really impressive.

Indeed using guides makes life easier; what I pointed out was rather that the fuselage, which is the most important item in a paintkit, could be simmetrical, but not everything else. I know that the logistics behind organizing tons of little uv-maps in a paintkit is an art of its own :smile:

> I have checked it, and both has absolutely the same size and proportions. The main wing has indeed some issues, but had never been intended and had been fixable if reported. 

My bad, I don't remember exactly when I came across it, but I don't think that's a big deal to be honest.

> Unfortunately there won't be next projects when things will go well and I can finance my Master degree course, which would start in some few weeks. And even if not - the work on the Cessna 182 consumes a lot of time for me already, and I only see new issues to fix. We provide payware quality without beeing payed for. So I feel more and more tired....

I understand that, Heiko, I also feel quite overwhelmed lately with all the FG work I am doing (c172p, c182 and particularly with the regional textures and materials). I kind of feel burned out as well... But look, we can always diminish the amount of work and take it easier, it doesn't have to be all or nothing. In the c172p project it's always the same situation: things slow down between releases, then it gets frenetic weeks before a merge into FGDATA. We both have been working on FG-related projects daily, and there is no problem in diminishing this. When I post something here for instance, you can feel free to take your time to answer, weeks if necessary.

On the bright side, this aircraft is looking stunning, I haven't seen this level of detail in a FG aircraft before, and I am proud to be able to help a little with it.
