### ISSUE TITLE
Idea/ Concept: place chocks/ safetycones/ fuel-trucks etc. via model-manager

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#55]
Place the chocks/ safetycones via model-manager like the walker

Advantage: 
- the model acts like a scenery model, will be recocgnized as collision object - no need for a workaround with the parking brake

- safety cones and other objetcs stays where they are placed (no flying trucks....)

Challenge: nasal script and making the objects remove from scenery  when not needed

Basic Idea: Walker

**Comment by HHS81** [comment]
Update:
took the code from the walker - and it works!! :smile:
The wooden-chocks.ac holds the aircraft at its place - even with full thrust!
The wooden-chocks keeps their position- even if the aircraft is moving. No flying trucks.... :yum: 

![nobrakes](https://cloud.githubusercontent.com/assets/12649375/13024766/9c0a3ed0-d1fa-11e5-9118-bc147c88289d.jpg)

Push soon

**Comment by HHS81** [comment]
Known Issue: 
the point of the ground reaction is exactly at the middle bottom of the wheel - that's explain the offset to the chocks in the picture. 

- FDM-wheels needs probably one more contact point?
- or a invisible collision object with an offset?

Guess the later makes more sense, the first one is more realistic but might be problematic on the normal ground....

**Comment by HHS81** [comment]
Known current Issue as well:
- possible interaction with a later added walker - have to test it

**Comment by gilbertohasnofb** [comment]
I'd say the yellow chocks would fit better, the idea of the wooden one is to look "improvised", just like one can expect to find in a bush plane in the middle of Alaska for instance :smile: 

As for the fuel-trucks, I don't think it's common to refuel these single engine planes with trucks, but rather using a gas pump in the airport, though I may be mistaken here.

**Comment by HHS81** [comment]
Hi,

yep, the yellow chocks are indeed better. 
The truck was just mentioned as an example. The whole thing is easy to implement, there is no bad interaction with the walker and no fps-impact. 
Maybe something for the c172p...

I found that today: http://www.aircraftspruce.eu/images/products/Airplane_Ready_to_Refuel_Small.jpg
Maybe?

The Cessna 182 allows external power supply, so at least a small ground power unit will be implemented, like I did for the EC 135 P2.

**Comment by gilbertohasnofb** [comment]
Sounds all good, but about the small refuel unit, how much fuel does that carry? Can you really fill two tanks with it?!

**Comment by HHS81** [comment]
Probably not much enough....but there are even bigger ones, pulled by cars.

Anyway, I think with the chocks we have already a nice feature. This feature is maybe more interesting for bigger aircraft like dhc6 or airliners. Imagine stairs placed via model-manager, and you can enter the aircraft  with the walker via the stairs....

**Comment by HHS81** [comment]
Had some troubles with the gui.....but solved after hours.

Just a ladder is missing, so Waldo can check Fuel Quantity and Fuel Filler Caps ....

![nobrakes2](https://cloud.githubusercontent.com/assets/12649375/13031371/ae883c9c-d2cc-11e5-8a58-ab254b10c2de.jpg)

**Comment by gilbertohasnofb** [comment]
If you need any help with the chocks//tie-downs/pitot tube cover logic and GUI, let me know (I did quite a lot of the work on them on the c172p). And by the way, your shots are incredible as always, that first shot is really beautiful!

**Comment by HHS81** [comment]
Thanks :smiley:
The problem was, that `dialog-apply` in combination with a setlistener applies the value to all sub-objects in the GUI. Took me a a lot of time to find out and how to solve this.

Now, a property is simply toggled via the GUI. This triggers a nasal-script who gets the position, orientation and altitude of the aircraft and places a model with this values applied in the scenery. The model is recognized as scenery-object by the aircraft, so there is a collision-detection (without crash). The model can be removed from scenery, and even be moved in runtime.

So actually at least for the chocks there is no complex logic needed. 

For the tiew downs I will need some help. As now, I understand that  a external force is used. But the whole logic behind looks rather complex to me- yesterday I failed to implement this. 

I will update today the missing ladder, and finally give the GUI a shape, so I would be happy if you then can give me help to the tie-downs.

**Comment by gilbertohasnofb** [comment]
Great!

> So actually at least for the chocks there is no complex logic needed. 

I think two of the reasons for the logic used in the c172p's chocks are: 1) there are two types of chocks used for different models, but more importantly 2) the chocks can be added both via the GUI menu but also by clicking on them. Is this still possible in your implementation?

> For the tiew downs I will need some help. As now, I understand that a external force is used. But the whole logic behind looks rather complex to me

Yes, to me as well, that part was done by onox, and I unfortunately don't have knowledge on how these external forces work :cry:

**Comment by gilbertohasnofb** [comment]
I had first implemented the tie-downs as static objects, but the problem was that when the aeroplane accelerates, it lowers the nose even if tied down (which is what is expected), and that code onox wroteis used partially to make the tie-downs "elastic" on a given point in the pavement.

**Comment by HHS81** [comment]
> I think two of the reasons for the logic used in the c172p's chocks are: 1) there are two types of chocks used for different models, but more importantly 2) the chocks can be added both via the GUI menu but also by clicking on them. 

The reason on the c172pis, that the chocks-models are not recocgnized as collision-objects, and tied to the aircraft-model. So there is a workaround with use of the parking-brake, which explains the rather complex logic. 

My solution just simply adds a model in the scenery, which physically acts like in real life. 
It is easy to implement, and another feature X-Plane don't have ! :bowtie:

>  Is this still possible in your implementation?

In the moment it can be only added via the gui, but I will add a click-spot, so it can be added and removed per click at the walk-around.

You wanna maybe try the branch `StaticElements` to see how it works. But it is still WIP- the GUI has not the format I prefer, and the StaticElements can be triggered in flight. Also the logic for the external-power needs changes in the electrical.nas. Will be fixed later today.

**Comment by HHS81** [comment]
> I had first implemented the tie-downs as static objects, but the problem was that when the aeroplane accelerates, it lowers the nose even if tied down (which is what is expected), and that code onox wrote is used partially to make the tie-downs "elastic" on a given point in the pavement.

Yep, that's pretty cool, hwo it works, really realistic!
I just don't understand how to implement it.

**Comment by HHS81** [comment]
- removed alpha-channel from textures
- added ladder-model
- added pitot-cover-model (from dhc6)
- dialogs for aircraft options, securing and ground-stuff
- removed unneded files

and I forgot:
- added clickspots to wheel-chocks. Currently the chocks can be removed at once, but can be done later if wanted (and would be a nice feature - imagine when one chock is forgotten to remove....:smile:)

Issues: dialog-apply removes walker and other objects loaded by model-manager. Don't use it!

Still WIP, I'll try again on the tie-downs...

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/12649375/13035787/3ad51e00-d358-11e5-88d3-dc32a0156d56.jpg)

**Comment by HHS81** [comment]
@gilbertohasnofb Finally added tie-downs - so ready for review!

**Comment by HHS81** [comment]
Another Promo-pic:
![fgfs-screen-005](https://cloud.githubusercontent.com/assets/12649375/13037960/2ce8b9c6-d38c-11e5-9add-5d387dc29873.jpg)
(yes, the ladder is already moved in the PR....)

**Comment by gilbertohasnofb** [comment]
Great pic! I will review the PR

**Comment by gilbertohasnofb** [comment]
Heiko, people are asking in the forum if you are tweaking those shots in the `README.md` file or not (adding blur, correcting colours and light, etc.). If so, personally I'd rather keep them untouched as to show what FG is really capable of.

**Comment by HHS81** [comment]
yep, the exterior shots had been tweaked. The interior shot uses the AO Map, which needs some improvements though

**Comment by gilbertohasnofb** [comment]
If you are up for it, let's avoid tweaking these promo shots then. I think in the right conditions the shots from FG hardly need any adjustments!

**Comment by HHS81** [comment]
o.k, the pic above is untweaked btw.... But I agree to someguy, that in some conditions a tweaking can improve the image

**Comment by gilbertohasnofb** [comment]
> But I agree to someguy, that in some conditions a tweaking can improve the image

Surely it does improve, which is exactly the problem! A tweaked image feels like "cheating" to me because you can't achieve that in the sim. I don't see much point in developing for a 3D application/game and then tweaking the "advertisement" screenshots (or to be frank, _any_ screenshots for that matter).

**Comment by gilbertohasnofb** [comment]
> o.k, the pic above is untweaked btw

:+1:

**Comment by gilbertohasnofb** [comment]
Heiko, I know I spoke against the fuel trucks, but it seems I was wrong, they are indeed used for refuelling this type of aircraft. See: 

![](http://2.bp.blogspot.com/_NfN_EWerqnQ/TEaDAgWXZlI/AAAAAAAAA2s/e7wdBtEPOt4/s1600/fuel.JPG)

![](http://www.cessna150.net/Assets/Photos/l_outside_photos/Refuling.JPG)

Also see: https://github.com/Juanvvc/c172p-detailed/issues/717#issuecomment-184181806

**Comment by gilbertohasnofb** [comment]
@HHS81 Also in that link from the c172p repository, onox is proposing some interesting things, please check it out when you have time

**Comment by HHS81** [comment]
yep, but not a small fiel in britisch columbia.... :smile: 

I thought more about something [like that:](http://i.ebayimg.com/images/i/151069853573-0-1/s-l1000.jpg) 
We have already a photorealistic model in the scenery model page, and can be visited in EDAU. 

At some point immersive realism is getting very difficult to create in flight simulator...

**Comment by gilbertohasnofb** [comment]
> At some point immersive realism is getting very difficult to create in flight simulator...

I agree with you, but both options are fine with me: I don't mind a truck in a small field as much as I don't mind a small portable tank being able to fill two full tanks. But that said, I think the truck solution is still better, though I will leave this up to you.

**Comment by gilbertohasnofb** [comment]
It's always possible to bring a truck to virtually any airfield in the world, but the same can't be said about a tiny tank fitting so much fuel

**Comment by HHS81** [comment]
The protable fuel tanks can be much bigger, the biggest one can hold 1000 gal, the smalles one 280 gal:[http://www.fuel-togo.com/trailers.html](http://www.fuel-togo.com/trailers.html)

**Comment by gilbertohasnofb** [comment]
Oh, in that case no problems at all!

**Comment by onox** [comment]
I have a patch here which fixes a problem with the right tie-down. It also defines three booleans to prevent them having an unspecified type. Changed the name in the license block of `Systems/c182s-ground-effects.xml` because the code it contains was written by me, not wlbragg.

Using the `StaticElements` branch, do `git am -s 0001-Fix-location-of-right-tie-down-in-FDM.txt` to apply the patch.

[0001-Fix-location-of-right-tie-down-in-FDM.txt](https://github.com/HHS81/c182/files/131244/0001-Fix-location-of-right-tie-down-in-FDM.txt)

**Comment by HHS81** [comment]
@onox 
Great, Thanks! :smiley:

**Comment by HHS81** [comment]
I have added a fueltanktrailer, and changed the code to use geo.put_model(), but does not save all too  much lines..... :disappointed: 
I need now to seperate each objects of the cones, ladder, and chocks - but it will still look like that:
![fgfs-screen-010](https://cloud.githubusercontent.com/assets/12649375/13445001/fd0f45a0-e009-11e5-90f7-625dcec8c4cc.png)

**Comment by gilbertohasnofb** [comment]
Really fantastic screenshot :smile:

**Comment by onox** [comment]
@gilbertohasnofb Do you want to add those cones, ladder, fuel tank to our project as well? Does the c172p has a need for that external power unit? If you add the models, you might want to add it to `Models/generic/` to indicate they can be re-used by other aircraft. (Ideally generic stuff should be added to fgdata, but the core devs are too slow and bureaucratic, and we can't easily modify the objects if they are in fgdata)

**Comment by gilbertohasnofb** [comment]
@onox I will open an issue for it, but I am afraid I can't do it right now, I am really busy with RL which is why I am a bit away from FG lately :cry:

**Comment by gilbertohasnofb** [comment]
> Ideally generic stuff should be added to fgdata, but the core devs are too slow and bureaucratic, and we can't easily modify the objects if they are in fgdata

Yes, that's the problem with adding things to FGDATA: it's a pain to modify anything.

**Comment by tigert** [comment]
Cool work.

I'd say one ladder that you move from wing to wing, there rarely are two. There is rarely a ground power unit used/needed for small planes like a C172.

A nice pic from a few years back. It's very nice to see the Cessna take its shape so well in Flightgear :-) Here we're putting the sticker on the tail of CTL.
![ladder](http://mik.1g.fi/kuvat/Tapahtumat%20-%20Vuosi%202011/CTL%2015000/IMG_1011.JPG/_full.jpg)

**Comment by gilbertohasnofb** [comment]
Very nice picture, @tigert, I love this livery :smile:

**Comment by HHS81** [comment]
> I'd say one ladder that you move from wing to wing, there rarely are two.

Unfortunately very difficult to solve. The object is "hard", so if it collide with the aircraft, the aircraft will crash. Moving around isn't easily possible with the method now used, and as object animation it will interfer with the ground. The only solution I see is to lift the ladder above the aircraft on the other side. I will try this though it isn't realistic.

**Comment by gilbertohasnofb** [comment]
What about hiding a ladder from one side when the other is activated? So then as far as the user is concerned, he can only have one ladder at a time, making him/her think it's the same ladder moving.

**Comment by HHS81** [comment]
one ladder, only left or right. It isn't technically possible to remove the "enable"-checkbox
![ladder](https://cloud.githubusercontent.com/assets/12649375/13576928/4c8fdf4c-e490-11e5-93ac-07b14f57d599.jpg)

**Comment by tigert** [comment]
How about two checkboxes if it is hard to do a radio button?

(X) ladder on left wing
( ) ladder on right wing

**Comment by gilbertohasnofb** [comment]
@tigert I think two checkboxes is a better solution, because you can have neither of them checked (as opposed to two radio buttons, in which one options is always checked). So with two checkboxes, we can have:

- if both are set to false, then stairs are removed
- if one is set to true, force the other to false and add a star to that respective side

Would that work, Heiko?

**Comment by HHS81** [comment]
@gilbertohasnofb @tigert 

- there is no real difference between checkboxed and radio buttons. Beside the style at least there is no one to my knowledge.

I had gilbertos idea was my goal, but I'm not sure yet if I'm able to do it.

**Comment by HHS81** [comment]
@gilbertohasnofb  @tigert O.k. I was able to do it - again kudos for the complete c172p-team for their work, as it was very helpful again! :smiley: :+1: 
No I only have to seperate the chocks models and the cones-models and make them clickable....

**Comment by gilbertohasnofb** [comment]
@HHS81 Great to hear that, Heiko! :smile:

**Comment by HHS81** [comment]
> if both are set to false, then stairs are removed
if one is set to true, force the other to false and add a star to that respective side
Would that work, Heiko?

After some thinking, I'm sure that wouldn't work since we can not set both to false with this method. 
Well I think keep my method this now as it is.

**Comment by gilbertohasnofb** [comment]
Sure, let's keep your method, but why wouldn't setting two checkboxes to false work? It's a simple condition to detect that AFAIK.

**Comment by HHS81** [comment]
@gilbertohasnofb 
Because: 

> if one is set to true, force the other to false and **add a star to that respective side**

Let's play this:
both button false = no ladders
left button true = left ladder, left radio/checkbox checked and  the right button false and no right ladder
right button true = right ladder, right radio/checkbox checked and left button false and no left ladder

and then both button again to false ? 

1.) The gui doesn't allow to check a radio/checkbox without doing anything.


2.) "_Unfortunately_" as well: the whole thing about is not making an object visible. The whole thing is about creating a model dynamically and placing it into the scene. That is what the script is doing. This is only working by a setlistener, otherwise you create thousand of instances of the same model. So you need to create the ladder as single model into the scene once and only like that- then it can be animated. 

So this what I did: I only create one model in the scene using the ladder.ac:

The setlistener registrates the checkbox is checked and creates the model. When unchecked it deletes the model from the scene. When clicking the radio-button in the dialog-box it will change the side by a simple animation. 

No need to have two ladder-models and hide one of them, no need to create another 30 lines of nasal-script for just another identical ladder-model, no need for fancy-complex nasal-scripts.

Simple, but still effective - the ladder will keep its place in the scenery - like in real life. But you can change the side where it will appear.

**Comment by HHS81** [comment]
Done!

**Comment by wlbragg** [comment]
@hbeni sorry to resurrect this closed issue, but I figured this was the best place to bring this to your attention. Even though it looks like this was not your work I wanted to bring up the idea reducing some code. I noticed the c182 uses a bunch of duplication of code for the ground equipment models. I had some fairly streamline code in place to place models, I think I picked it up originally from the space shuttle. I used it though when introducing your c182 ground services instead of looking at how you placed modeles here. While I was looking at some other systems in place for your ground equipment I noticed how the models were placed here and that there was a lot of extra code compared to the model placement code I use in most of the aircraft I work on. If you compare it to how it is done in the c182 you'll see the difference and notice how much unnecessary duplicate code is used. Anyway, I'm just letting you know there is a more streamlined way to do it. I have no idea if it saves any resources or real overhead, but I wanted to bring it to your attention anyway. 

This is the basics of it I am using in the AirCrane. In the Cub and the 172 there are some custom modifications for other ground equipment like the mooring anchor.

~~~
############################################
# Static objects: mooring anchor
############################################

var StaticModel = {
    new: func (name, file) {
        var m = {
            parents: [StaticModel],
            model: nil,
            model_file: file
        };

        setlistener("/sim/" ~ name ~ "/enable", func (node) {
            if (node.getBoolValue()) {
                m.add();
            }
            else {
                m.remove();
            }
        });

        return m;
    },

    add: func {
        var manager = props.globals.getNode("/models", 1);
        var i = 0;
        for (; 1; i += 1) {
            if (manager.getChild("model", i, 0) == nil) {
                break;
            }
        }
        var position = geo.aircraft_position().set_alt(getprop("/position/ground-elev-m"));
        me.model = geo.put_model(me.model_file, position, getprop("/orientation/heading-deg"));
    },

    remove: func {
        if (me.model != nil) {
            me.model.remove();
            me.model = nil;
        }
    }
};

StaticModel.new("coneR", "Aircraft/AirCrane/Models/Ground-Equipment/safety-cone/safety-cone_R.xml");
StaticModel.new("coneL", "Aircraft/AirCrane/Models/Ground-Equipment/safety-cone/safety-cone_L.xml");
StaticModel.new("gpu", "Aircraft/AirCrane/Models/Ground-Equipment/external-power/external-power.xml");
StaticModel.new("ladder", "Aircraft/AirCrane/Models/Ground-Equipment/ladder/ladder.xml");
StaticModel.new("fueltanktrailer", "Aircraft/AirCrane/Models/Ground-Equipment/fueltanktrailer/fueltanktrailer.ac");
StaticModel.new("externalheater", "Aircraft/AirCrane/Models/Ground-Equipment/external-heater/RedDragonEnginePreHeater.ac");
~~~

Also I noticed something else I will likely change. The 182 uses a timer to check for aircraft movement to remove some of the ground models. Probably not as efficient as a listener. If you decide to make any changes to the c182 and make an issue I can add any other optimizations opportunities I happen to notice.

And while I am at it, I also want to thank all involved for the Ground Services work. It is really cool and I am adding it to the Cub and AirCrane. I haven't added attributes to the creators yet, but I will before it is all done.

**Comment by wlbragg** [comment]
One more thought. It just dawned on me how much work I am duplicating for each aircraft just adding the ground services systems. This whole system might be a good candidate for an Addon. The main issue would be the connections to the electrical, and fuel systems of each individual model and the placement, size, and brand name of the ground equipment used. But it is really tempting.
