### ISSUE TITLE
switches are not animated

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#56]
The switches on the panel are not animated and textured.

**Comment by gilbertohasnofb** [comment]
Let me know if you need textures for them.

**Comment by HHS81** [comment]
I wonder where I should put them on the uvmap

**Comment by gilbertohasnofb** [comment]
There is still some tiny places in the main panel texture (such as in the holes of the engine gauges). Since all switches will have the same metallic look (right?) we can simply add a single switch to one of those holes.

**Comment by HHS81** [comment]
How should I uvmap them?
looking directly on it, or from side view?

**Comment by gilbertohasnofb** [comment]
Probably top view (then mirror the texture on the bottom). See for instance the texture used in the c172p: 

![untitled](https://cloud.githubusercontent.com/assets/5700795/12706023/2909e4d0-c87c-11e5-83b1-0d4f21d1486e.jpg)

**Comment by HHS81** [comment]
Thanks!

**Comment by gilbertohasnofb** [comment]
My pleasure!

**Comment by gilbertohasnofb** [comment]
Heiko, what do you think if we do things a bit differently this time: what if I just add this switch texture to the file, and then you use it as source for mapping? Would that work for you?

**Comment by HHS81** [comment]
Yep, that would be perfect!

**Comment by gilbertohasnofb** [comment]
Ok, it's done! As for the liveries, I will check that paintkit in the next days as soon as I have some time

**Comment by HHS81** [comment]
see PR #65 for review
