### ISSUE TITLE
EGT and Oil gauge not quite right scaled

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#57]
scale both gauges

**Comment by HHS81** [comment]
Done

**Comment by gilbertohasnofb** [comment]
There are some problems with the new gauges which may be related to this, see: https://github.com/HHS81/c182/issues/58

**Comment by HHS81** [comment]
both gauges are ready for a review - see PR

**Comment by gilbertohasnofb** [comment]
:+1: I will do it right now!

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/HHS81/c182/pull/60
