### ISSUE TITLE
Engine gauges texture problems

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#58]
There are some problems with the new engine gauges, see: 

Everything marked in yellow is either cut or too close to the borders. Everything marked in purple have being UV-mapped into two different heights which can be seen from some angles (look at the PSI text in the image for instance):

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12719594/53033f64-c8f6-11e5-9da4-4f5756b00dd3.jpg)

**Comment by HHS81** [comment]
Please see also #61

**Comment by gilbertohasnofb** [comment]
https://github.com/HHS81/c182/pull/60 has fixed part of the issue, so now it's missing the label FUEL in the fuel gauge (which I didn't circle above but I think it's too close to the border) and the VAC AMP gauge.

**Comment by HHS81** [comment]
see PR #62

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/HHS81/c182/pull/62
