### ISSUE TITLE
Confusing textures for flaps

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#63]
Currently all our instrument textures are located inside `c182/Models/Instruments`, while our flaps texture is located at `c182/Models/`. Moreover, the directory `c182/Models/Instruments` does contain a file named `flaps.png`, which seems to be corrupted and is not in use. I suggest that we:

- delete `c182/Models/Instruments/flaps.png`
- move `c182/Models/flaps.png` to `c182/Models/Instruments`
- apply this directory change to the model in Blender and re-export

**Comment by HHS81** [comment]
In Blender you can't apply textures when they are not in the same folder. I know some .xml-magic which could do the trick, but since the flaps isn't an instrument I would better keep the texture in c182/Models/flaps.png.

So I delete the corrupted file in  `c182/Models/Instruments/flaps.png`

but keep` c182/Models/flaps.png`

**Comment by HHS81** [comment]
see PR #64

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/HHS81/c182/pull/64

**Comment by gilbertohasnofb** [comment]
Thanks Heiko! Just two things:

- you forgot to write "Fixes #63" on the PR, which would have closed this issue automagically :wink: 
- I think there is a way in Blender to use textures in different folders, if I am not mistaken that's how the c172p is doing now. But anyway, let's keep that file wherever you think is good, I have no opinions on that at all

**Comment by HHS81** [comment]
> you forgot to write "Fixes #63" on the PR, which would have closed this issue automagically :wink:
Damn, I'm still not used to this....

> I think there is a way in Blender to use textures in different folders, if I am not mistaken that's how the c172p is doing now. But anyway, let's keep that file wherever you think is good, I have no opinions on that at all

No, the whole 3d-model is in a different folder. FlightGear allows to specify a texture path, but I think it is o.k. to keep the flaps panel where it is

**Comment by gilbertohasnofb** [comment]
:+1:
