### ISSUE TITLE
Make use of procedural lights

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#68]
Make use of procedural lights for:

- Navlights red, green, tail
- Strobe

- Beacon (if offset can be defined)

not for landing or taxilight - I like those textures :heart_eyes:

Test available at: [https://github.com/HHS81/c182/tree/newlights](url)

**Comment by gilbertohasnofb** [comment]
Great, I will test them soon :smile: (and yes, your landing and taxi lights are amazing!)

**Comment by gilbertohasnofb** [comment]
Looks good, but I found some problems with the lights in general:

- maybe the tail light has to be moved slightly backwards as there is a black dot in its centre (is that the fuselage colliding with it?)
![fg-0](https://cloud.githubusercontent.com/assets/5700795/12790709/e51c5dfa-caa3-11e5-8081-ede5ce78c3d5.jpg)

- same is true for the strobes
![fg-3](https://cloud.githubusercontent.com/assets/5700795/12790711/e52517ec-caa3-11e5-9c27-760601aa8541.jpg)

- strange triangle inside the beacon
![fg-1](https://cloud.githubusercontent.com/assets/5700795/12790710/e51dd248-caa3-11e5-917b-193adc814114.jpg)

- strange red light above the antennas, what is that?
![fg-2](https://cloud.githubusercontent.com/assets/5700795/12790712/e524cc92-caa3-11e5-984a-8e8c94ae40cf.jpg)

- IMO, the nav lights should be stronger, I can barely see them now during the day.

**Comment by HHS81** [comment]
Lol, the strange red light is the new procedural light testing the angles.
All other lights are the one we were used to. No change on that yet.
Those artifacts you mentioned I've never seen. Especially not on the beacon.

**Comment by gilbertohasnofb** [comment]
Lol :stuck_out_tongue_winking_eye: :dizzy_face: facepalm...

Anyway, I have not seen those artifacts before either! I have no idea what is causing them, but if we plan to move on to the procedural lights it won't matter anyway. But it's really strange how the nav lights look so dim now, but maybe I got used to how the look on the c172p after so much testing there.

But about the procedural light: the effect is really cool, but what I deeply dislike on it is that the centre is not completely white like our png lights, but rather a shade of red. Thorsten actually made this modification to all lights, and I think they look so much worse then before. But I remember some people complaining they couldn't make the colour of the PAPI lights out, so I can't completely blame him. But it would be great if we can tweak these, as the png lights are still looking better IMO.

**Comment by HHS81** [comment]
> `But about the procedural light: the effect is really cool, but what I deeply dislike on it is that the centre is not completely white like our png lights, but rather a shade of red. 

You can define it, even per runtime if you want, I just simply didn't it here. 

> Thorsten actually made this modification to all lights, and I think they look so much worse then before. But I remember some people complaining they couldn't make the colour of the PAPI lights out, so I can't completely blame him. But it would be great if we can tweak these, as the png lights are still looking better IMO.`

Well, I was one of them. I admit, it indeed looked much better before. The problem is: with desaturating the colors itselfs needs adjustements, especially red. Unfortunately the scenery lights are hardcoded (Simgear?).
Here on the aircraft procedural light we can adjust the colors to our liking. I just wanted to test the angles. Unfortunately, we can't get more than 180deg. It is o.k. for aircraft lights, but probably not on ships.

**Comment by gilbertohasnofb** [comment]
Okay!

**Comment by HHS81** [comment]
making it white in the middle gives us a star effect - who is brave enough to ask him to allow also the use textures instead of shader magic?

**Comment by gilbertohasnofb** [comment]
> who is brave enough to ask him to allow also the use textures instead of shader magic?

hahaha :laughing: I am already involved in some changes to the airfield effect and I have been a pain in his neck, so I dare not!

**Comment by HHS81** [comment]
updated branch "newlights" again:
- made use of procedural lights for all lights (without taxi and landinglights)
- made them dependant from the used renderer

What I learned today:
- I don't like the star effect and would like to see that I'm able to use my own textures.
- it IS possible to create wider angles than 180deg - by using two light-quads and a seperate effect for each of them defining different angles. Already done on the tail-navlight. Maybe I will do that for the strobes.
- you can define offsets by shifting the quad in blender  x-axis
- a full effect folder

What I have to say: great addition! But I don't like the star effect! Did I say already? I don't like it....
That's why I will add a switch where you can select both..... :stuck_out_tongue: :innocent:

Strobes, navlights with too much offset
![strobes](https://cloud.githubusercontent.com/assets/12649375/12800150/5bad55c6-cad3-11e5-9d68-9bc8543fcbf2.jpg)

Beacon and navlights
![beacon_navlights](https://cloud.githubusercontent.com/assets/12649375/12800156/63a1447c-cad3-11e5-93e7-6b1255ae7bbb.jpg)

**Comment by gilbertohasnofb** [comment]
> What I have to say: great addition! But I don't like the star effect! Did I say already? I don't like it....

I am with you 100% here. And not only regarding the aircraft lights, but the scenery lights as well...

By the way, that second shot of yours above looks amazing, I hope you won't mind but I will post it in the forum :smile:

**Comment by HHS81** [comment]
Ready for review

**Comment by HHS81** [comment]
![fgfs-screen-005](https://cloud.githubusercontent.com/assets/12649375/12900306/e793f0be-ceb5-11e5-97dd-50fbd4419c7c.jpg)

![fgfs-screen-006](https://cloud.githubusercontent.com/assets/12649375/12900298/e2b97e10-ceb5-11e5-9e7a-bd6921c20a89.jpg)
