### ISSUE TITLE
Better UV map of the Attitude Indicator

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#72]
Quoting from the c172p project:

> I believe we need a better UV map of the Attitude Indicator. For some reason, the straight lines get angled in the corners, see:
>
> ![](https://cloud.githubusercontent.com/assets/3361585/12906964/131d2252-cee6-11e5-9675-60ebc0f05291.png)

The UV-map was fixed in that project, so I will copy it here as well.

Ref: https://github.com/Juanvvc/c172p-detailed/issues/373

**Comment by gilbertohasnofb** [comment]
Hmm, that doesn't work well because the model of the AI in the c172p has changed now. I think we will have to re-UV map it ourselves.

**Comment by HHS81** [comment]
O.k., I'll try it to remap....

**Comment by gilbertohasnofb** [comment]
Much better!
