### ISSUE TITLE
Holes in the horizontal stabilizer

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#75]
Question: what are these holes in the horizontal stabilizer? Is this intentional?

![fgfs-screen-001 55](https://cloud.githubusercontent.com/assets/5700795/13036166/56c43652-d360-11e5-8a5a-9417e5df08f5.png)

**Comment by HHS81** [comment]
Yes, intentional.
I can't say how large this is in cm, but the hole is there on the real aircraft:
![image](https://cloud.githubusercontent.com/assets/12649375/13036223/811dddda-d361-11e5-88e3-7d47f9c43a2e.png)

So it is a won't fix

**Comment by gilbertohasnofb** [comment]
Oh, I couldn't find a photo from that angle, but that said it's all god! :+1:
