### ISSUE TITLE
List of interesting Cessna 182 S-Variants liveries

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#76]
Here a list of interesting Cessna 182 S-Variants Liveries:

- The first Cessna 182 S, and first Cessna 182 after more than 10years out of productions:
 http://www.flyperformance.com/aircraft/cessna-n182fn/:
 ![image](https://cloud.githubusercontent.com/assets/12649375/13036293/c32e7b42-d363-11e5-92b4-8243e562fd26.png)

- HB-CQP:
http://www.airliners.net/search/photo.search?regsearch=HB-CQP&distinct_entry=true
![image](https://cloud.githubusercontent.com/assets/12649375/13036304/1b4d850c-d364-11e5-980e-8cce380f2ea6.png)

- N182PJ:
http://www.airliners.net/photo/Cessna-182S-Skylane/2626013/L/&sid=d1262838da8035a0e2fc88221514b46f
![image](https://cloud.githubusercontent.com/assets/12649375/13036311/45de81e0-d364-11e5-9454-0e7583b48626.png)

- N311HP
http://www.airliners.net/photo/Ohio-State-Highway/Cessna-182S-Skylane/0606498/L/&sid=4ff349902a6a13269a6a62044e43e448
![image](https://cloud.githubusercontent.com/assets/12649375/13036415/1fd88204-d367-11e5-9330-11d872bf62bc.png)

- D-EPLZ
![image](https://cloud.githubusercontent.com/assets/12649375/13036337/09fdf66e-d365-11e5-9bea-410a9418bc08.png)

- D-EBKI
![image](https://cloud.githubusercontent.com/assets/12649375/13036355/aa230a6c-d365-11e5-86c8-cf69a01dcaca.png)

- HB-CZV
![image](https://cloud.githubusercontent.com/assets/12649375/13036399/a1b449da-d366-11e5-9afc-96bec5f6bca2.png)

- N321HW
![image](https://cloud.githubusercontent.com/assets/12649375/13036404/d76537e2-d366-11e5-89e8-a4ecb0c63909.png)
![image](https://cloud.githubusercontent.com/assets/12649375/13036408/e85c52e2-d366-11e5-905f-d18ea7f5a68a.png)

**Comment by gilbertohasnofb** [comment]
Thanks a lot, Heiko! I will work on some of these soon :smile:

**Comment by gilbertohasnofb** [comment]
Heiko, can you confirm that N339ME is a model S, please? 

![](http://www.us.all.biz/img/us/catalog/132522.jpeg)

![](http://www.aircraftmerchants.com/images/44589CBA-0C34-424E-985A-B1849F06512D/2.jpg)

more info: http://www.westerncardinal.com/sales/n339me/index.shtml

**Comment by HHS81** [comment]
Yes, it is a so called MIllemnium Edition - a special edition. Maybe a different avionics, I can see a HSI. The S-Models had been only built between 1996 and 2001. Everthing later until today were T-Models

**Comment by gilbertohasnofb** [comment]
In that case, I will just leave it aside.

**Comment by gilbertohasnofb** [comment]
Thanks, by the way :+1:

**Comment by HHS81** [comment]
Well, it is a Cessna 182 S Millenium Edition. Like Cars - as an example there is a Ford Focus - and the special edition Ford Focus RS. But both are Ford Focus.
The Cessna 182 S Millenium Edition were built 2000 - that's why _millenium_ edition
