### ISSUE TITLE
remove prop cone holes from AOMap

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#80]
Remove prop cone holes from AOMap, as when the propeller starts spinning it leads to this ugly results:

![untitled](https://cloud.githubusercontent.com/assets/5700795/13048005/3095b81a-d3e3-11e5-8754-8cf01d6620de.jpg)

@HHS81 would you be able to fix the paintkit? I would then fix the affected liveries.

**Comment by gilbertohasnofb** [comment]
And by the way, how do you create those beautiful AOMaps? I am **really** impressed with your paintkit

**Comment by HHS81** [comment]
Noticed yesterday, easy to fix.

> And by the way, how do you create those beautiful AOMaps? 
[Simply like that](http://wiki.flightgear.org/Howto:Add_smooth_(%22Ambient_Occlusion%22)_shadows_in_Blender)

But a bit more enhanced, since I use Blender Cycles and added a ground to make the bottom surface of the aircraft more darker.

**Comment by gilbertohasnofb** [comment]
:+1: let me know once this is fixed so I can update those liveries in the same PR

**Comment by HHS81** [comment]
sure

**Comment by HHS81** [comment]
Done!

**Comment by gilbertohasnofb** [comment]
Thanks! So I will fix those liveries tonight!

**Comment by gilbertohasnofb** [comment]
done, see the PR
