### ISSUE TITLE
Remove unecessary files

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#84]
Are the files `/Models/FuselageTexturing.png`, `/Models/Texturing-Interior.xcf` and `/Models/UVmap.png` still necessary? Can we remove them?

**Comment by HHS81** [comment]
Are the files /Models/Texturing-Interior.xcf and /Models/UVmap.png already removed in branch `StaticElements`, the other file I will do

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
What about the liveries? Default "1" looks great, but do you want to keep defaul2 and default3? If so, I would say we need to apply the AOMap to it.

**Comment by HHS81** [comment]
Default 1 will be kept, (maybe a bit improved adding the cessna emblem), the oner onnes I will delete, as they were only made for testing.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
It seems all these files were removed except for `/Models/FuselageTexturing.png`. Do you still need it?

**Comment by HHS81** [comment]
I don't think we need, it shows the uvmap

**Comment by gilbertohasnofb** [comment]
Ok, I will make a PR to remove it.

**Comment by gilbertohasnofb** [comment]
Done, see: https://github.com/HHS81/c182/pull/116
