### ISSUE TITLE
strong pull to the right during take off roll

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#85]
I always feel a strong pull to the right during take off roll and often I am applying near to full rudder to keep the aircraft in the runway. Once the aircraft leaves the ground, it immediately tries to go to the left (given the near full rudder). Is this behaviour normal/intended?

**Comment by HHS81** [comment]
I can't tell, I'll investigate

**Comment by gilbertohasnofb** [comment]
Ok

**Comment by HHS81** [comment]
I know that currently forward slips aren't possible. It is on my to-do-list. I already tried, but the real values I used makes the aircraft very sensible. Needs a while....

**Comment by gilbertohasnofb** [comment]
Heiko, if you'd like we can contact Dany (dany93 from the c172p project). He is very knowledgeable with FDMs overall and he implemented the stall behaviour in the 172. Maybe he would be interested in taking a look here and giving his opinion.

**Comment by HHS81** [comment]
I had a look, and I can't reproduce this issue.
There is a little pull to the right and a stronger to the left, when the gear is leaving the ground. That's due to p-factor. At least this is to strong, and I have another fdm here on my system which improves this. Nethertheless, with this fdm I don't get the ability for a forward-slip. Actually I can set the fdm between "no-strong-p-effect" and "ability forward-slip". The first one has real coefficients, the latter not.
But until now I can't have both.

**Comment by gilbertohasnofb** [comment]
Ok Heiko, I will try to see how reproducible it is and report back. But I did not meant the moment the gear is about to leave the ground, but rather the whole take off roll.

**Comment by HHS81** [comment]
hmmm.... on ground I can only imagine that the brakes are pressed accidently. They are coupled with the nosegear and will increase the steer angle (like in real). 
But yesterday I noticed that the rudder trim is not set to zero, and it has a quite large influence. 
Well, like I said, there is a fdm in progress, which schould fix this.

**Comment by HHS81** [comment]
It seems I coming the solution nearer.... :smiley:

**Comment by gilbertohasnofb** [comment]
Heiko, sorry for not replying for the last message here, I haven't had much time with FG lately. I still observe this strong right pull during the take off roll but not all the time, and I can't narrow down what is the problem: I know it's not due to the rudder trim as I have seen this happening while the trim is centred. It's also not related to the brakes. I am trying to test which wind conditions affect this, but I have seen the right pull even when the wind is coming FROM the right.

**Comment by HHS81** [comment]
can you make a screenshot while this happing from cockpit view?

**Comment by HHS81** [comment]
Please test also branch `FDM` which fixes some issues

**Comment by gilbertohasnofb** [comment]
Ok Heiko, I will try to do that today. The thing is my system updated the graphic driver and things didn't go as plan, and right now I am having troubles executing any 3D program. I will try to solve this tonight and hopefully test all this!

**Comment by HHS81** [comment]
No problem, take your time to fix your graphic driver.

**Comment by gilbertohasnofb** [comment]
Hi Heiko

**Comment by HHS81** [comment]
And that is what issue?

**Comment by gilbertohasnofb** [comment]
So, the problem is still there. Have a look at these images:

1) the wind is coming from the right, so if anything the wind should send the aircraft to the LEFT, not to the RIGHT:
![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/13442205/481787b0-dffb-11e5-84fe-ec5171135f2b.png)

2) trims are neutral, so are the brakes and the control surfaces:
![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/13442216/54b9c474-dffb-11e5-9b21-70cf82d6dddb.png)

3) start to accelerate, the aircraft turns extremely fast to the right. If I don't compensate with almost full left pedal, I go out of the runway very very fast. 
![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/13442241/6fa85fac-dffb-11e5-8ffb-a8f4273fd39a.png)

If you can't reproduce it, I will try to make a video of this behaviour later on, but unfortunately I am still having issues with my system :sob:

**Comment by HHS81** [comment]
O.k. Thanks. I'll take a look

**Comment by HHS81** [comment]
Can reproduce it, and the effect is even expected. But not that strong.

**Comment by gilbertohasnofb** [comment]
> Can reproduce it

Great!

> and the effect is even expected. But not that strong. 

What do you mean expected? In the situation above, with the wind coming from the right and pushing the aircraft left, together with the P-factor also sending the aircraft to the left, how is this behaviour expected?

**Comment by HHS81** [comment]
@gilbertohasnofb 
It is probably 50% fdm and for sure 50% pilot error :smile: :

When Taxing/starting in crosswind you have to put the ailerons up into the wind - wind from right --> yoke right. Wind from left --> yoke left.
To keep the aircraft on the runway straight you have to compensate this with the rudder.
See this diagram (for taxiing) from the POH:
![image](https://cloud.githubusercontent.com/assets/12649375/13442966/07495b9c-dfff-11e5-8774-f1bdbe9bc6b4.png)
The POH also states: 

> _With the ailerons
partially deflected inlo the wind, the airplane is accelerated to a
speed slightly higher than normal, then pulled off briskly to prevent
possible settling back to the runway while drifting. When clear of the
ground, make a coordinated turn into the wind to correct for drift.
_
At a certain wind speed you indeed run out of rudder/ nose gear, but I wouln'd expect this at 15ktn wind speed. And not the pitch up when release brakes with full power.

**Comment by gilbertohasnofb** [comment]
I always thought this was needed only for taxing, but that you shouldn't do it during the take off roll. Still, if the wind comes from the right, there is no way that the aileron position will send you to the right!

**Comment by HHS81** [comment]
It is needed for take-off and recommended for landing. We had this discussion these days at c172p-project. 
But the needed rudder-input is too much here - I'll just investigate why....

**Comment by gilbertohasnofb** [comment]
Heiko, my point is that only only the amount of input seems incorrect, but also the direction of it. It seems to me that the situation I observed in the sim is physically impossible.

**Comment by HHS81** [comment]
No, there are two reason:
1.) wind is pushing against the vertical stab -. it will turn  the aircraft around the CG, and with that into wind seen from pilot view.
2.) aileron into wind will also turn the aircraft into wind.

Nethertheless I found the issue: I didn't pushed the right file.

**Comment by HHS81** [comment]
@gilbertohasnofb 
Pushed now the right file into branch `master`
Please test

**Comment by gilbertohasnofb** [comment]
Now that's more like it! :+1:

**Comment by HHS81** [comment]
@gilbertohasnofb 
Wind speed 20ktn at ground (25ktn at 100ft and more):
![fgfs-screen-008](https://cloud.githubusercontent.com/assets/12649375/13443939/cbc4b670-e003-11e5-8edd-2c67cad6e51e.png)
![fgfs-screen-009](https://cloud.githubusercontent.com/assets/12649375/13443941/d31632aa-e003-11e5-89fa-0568bec60575.png)

You can even start and land at higher speeds as the images shows. 
And yes, that's realistic! :smiley:

**Comment by gilbertohasnofb** [comment]
:fearful:
