### ISSUE TITLE
Nav Lights quad showing in FGRun

### ISSUE THREAD

**Issue by wlbragg** [HHS81/c182#87]
Needs a nopreview tag. I looked at the code but couldn't find where the procedural-light object was being introduced. The tag failed to work on red-navlight, etc.
![preview](https://cloud.githubusercontent.com/assets/11069680/13067553/e293f146-d436-11e5-84f5-025d0c4f5e63.jpg)

**Comment by HHS81** [comment]
@wlbragg  Thanks for this report!
The tag should goes into ../Effects/*light.xml. I added the tag also to the clickspots.

**Comment by HHS81** [comment]
@gilbertohasnofb  PR ready for review

**Comment by gilbertohasnofb** [comment]
I will test it right away!

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/HHS81/c182/pull/99
