### ISSUE TITLE
rethink Milestones

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182#89]
In the moment I see more and more issues to be fixed, and added to the FGAddon milestone. 
But the more and more we add, the less we get to be done.

Release early, release often - when I compare how far the Cessna 182 S is compared to other aircraft in FGAddon we are really far. Maybe not like the Cessna 172p yet, but more than other certain aircraft.

**Comment by gilbertohasnofb** [comment]
You are right, Heiko. Maybe we can create a second milestone called "FGAddon Release 2" and move some issues over there, what do you think?

**Comment by HHS81** [comment]
Yep, that sounds o.k.

I think the same about the priorities.
Maybe it is better to only have up to 4 issues with high priorities, and set the other ones to middle and low. If all 4 issues with high priotity are fixed, the lower ones will move up.

**Comment by gilbertohasnofb** [comment]
Sounds good. In that case, I think we can close this, right?
