### ISSUE TITLE
create ALS exterior shadow

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#92]
create ALS exterior shadow

**Comment by HHS81** [comment]
@gilbertohasnofb 
![fgfs-screen-005](https://cloud.githubusercontent.com/assets/12649375/16710392/82db3576-462c-11e6-9467-ca52bad1fe26.png)

**Comment by gilbertohasnofb** [comment]
@HHS81 :clap: :clap: :clap:
