### ISSUE TITLE
create ALS panel shadow

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#93]
create ALS panel shadow using a cube map

**Comment by HHS81** [comment]
@gilbertohasnofb 
![fgfs-screen-001](https://cloud.githubusercontent.com/assets/12649375/16710316/5317c0f4-462a-11e6-931c-445ba792f234.png)

Need to remove the sunshades from the cubemap

**Comment by gilbertohasnofb** [comment]
This is looking great. I'd love to see it from an angle in which the panel is half in the shadow half in the sun (this image has it almost completely in the shadow). Also, something that we did in the c172p project was to add a tiny bit of blur to the cubemap, so that the shadow edges are a bit more softer.

**Comment by HHS81** [comment]
@gilbertohasnofb 
![fgfs-screen-008](https://cloud.githubusercontent.com/assets/12649375/16710774/49d6312c-463b-11e6-9a76-c1426b3a09ef.png)

**Comment by gilbertohasnofb** [comment]
Gorgeous screenshot!
