### ISSUE TITLE
create ALS landing lights

### ISSUE THREAD

**Issue by gilbertohasnofb** [HHS81/c182#94]
create ALS landing lights

**Comment by gilbertohasnofb** [comment]
@wlbragg would you be able to point to me where the ALS landing light is defined in the c172p? I am having a hard time trying to figure it out by myself... :cry: I understand how the property `/sim/rendering/als-secondary-lights/use-landing-light` is created, but it seems to be used nowhere else than the file `als-lights.xml`, and so I don't see how that turning true activates the effect.

**Comment by gilbertohasnofb** [comment]
@wlbragg please ignore that, I just read the ALS technical notes and I realise that was not some property you created, but actually a property that is tied directly to the landing lights and setting it to true is enough to turn the ALS landing lights on... (we need a facepalm emoji on GitHub)

**Comment by wlbragg** [comment]
:+1:
